### ISSUE TITLE
Cumulative RDF is incorrect for different arrays

### ISSUE THREAD

**Issue by mphoward** [glotzerlab/freud#1037]
### Description

The cumulative RDF (`RDF.n_r`) does not give the expected values if different arrays are used for the system & query points, and the arrays don't have the same shape.

I think that in this line:
https://github.com/glotzerlab/freud/blob/aa7f09a9716290172dd3bb3e764164ef4479dea4/cpp/density/RDF.cc#L77
the prefactor should use the number of query points rather than system points, so that the average is taken over query points.

### Steps to Reproduce

```python
import numpy as np
import freud                                                                         

L = 12. 
box = freud.Box.from_box([L, L, L])
rdf = freud.density.RDF(10, 5.)

rng = np.random.default_rng()
ri = L*rng.uniform(low=-0.5, high=0.5, size=(10, 3))                                 
rj = L*rng.uniform(low=-0.5, high=0.5, size=(20, 3))                                 

# same
rdf.compute(system=(box, ri), query_points=ri)
n_r = np.cumsum(rdf.bin_counts/ri.shape[0])
print(np.allclose(n_r, rdf.n_r))

# different
rdf.compute(system=(box, rj), query_points=ri)
n_r = np.cumsum(rdf.bin_counts/ri.shape[0])
print(np.allclose(n_r, rdf.n_r))
```

### Error Output

```shell
Current output is:

True
False

but it should be:

True
True
```

### freud Version

v2.11.0

### Python Version

v3.10.5

### System Platform

Linux

### Installation method

Download from conda-forge

### Developer

Would someone else please fix this?

**Comment by tommy-waltmann** [comment]
Thanks for reporting this! It should just be a one or two line fix.

**Comment by mphoward** [comment]
No problem! Yes, I agree, I just don't have time to implement the fix & test. Thanks for taking care of it!
