### ISSUE TITLE
freud.order.SolidLiquid.compute() does not return self

### ISSUE THREAD

**Issue by WouterNed** [glotzerlab/freud#1060]
### Description

Hi! The method freud.order.SolidLiquid.compute() does not return self, while the documentation implies it does? Instead, it returns a NoneType Object. The object itself is changed though, so there is a workaround to compute, but you have to disregard the output.

### Steps to Reproduce

```python
import numpy as np
import freud

L = 10
num_points = 100

points = np.random.rand(num_points, 3)*L - L/2
box = freud.box.Box.cube(L)

neighs = freud.locality.AABBQuery(box,points).query(points, dict(r_max=2.1)).toNeighborList()

result = freud.order.SolidLiquid(6, 0.7, 8, False).compute((box,points),neighs)

# workaround
# result1 = freud.order.SolidLiquid(6, 0.7, 8, False)
# test = result1.compute((box,points),neighs)
# result2 = result1.num_connections
```

### Error Output

```shell
The above code would result in the variable "result" being of the type "NoneType", while it is supposed to be of the type "order.SolidLiquid". If a property is called you would get the error:

AttributeError: 'NoneType' object has no attribute 'num_connections'
```

### freud Version

v2.12.1

### Python Version

v3.10.6

### System Platform

Linux

### Installation method

Download from PyPI

### Developer

Would someone else please fix this?

**Comment by tommy-waltmann** [comment]
Thanks for bringing this to our attention. After looking through the codebase again, I realized we also made the same mistake in the `EnvironmentMotifMatch` class. I'll have a PR up soon to address this.
