### ISSUE TITLE
Diffraction pattern is related to box shape

### ISSUE THREAD

**Issue by zhangyemayapro** [glotzerlab/freud#1086]
### Description

I'm dealing with a system composed of particles comfined in a circle and particles have arranged themselves into a triangular lattice. But I find that, the diffraction pattern is related to the box（I set a elongate box）. Shouldn't the diffraction pattern independent of box? 

![image](https://user-images.githubusercontent.com/32811826/228151055-150a51cb-024a-40d5-bf01-0cc38c5e4d31.png)

![image](https://user-images.githubusercontent.com/32811826/228151101-972ed0a0-ba29-4f0c-97af-8840fd05dfd6.png)

### Steps to Reproduce

```python
from matplotlib import pyplot as plt
import numpy as np
import freud
uc = freud.data.UnitCell.hex()
n_repeats = (20, 20,1)
system = uc.generate_system(n_repeats)
position=system[1]
position=position[np.linalg.norm(position,axis=1)<10]
box=np.array([20., 40.,  0.,  0.,  0.,  0.], dtype="float32")
system=(box,position)

sf=freud.diffraction.DiffractionPattern(grid_size=512)
sf.compute(system,peak_width=1)
```

### freud Version

v2.8.0

### Python Version

v3.10.4

### System Platform

Linux

### Installation method

None

### Developer

None

**Comment by tommy-waltmann** [comment]
Hi @zhangyemayapro , the error output is not rendering properly, so I cannot see what the error message is. Something to note is that the `DiffractionPattern` class currently only works for cubic boxes, there is a note about this in the [documentation](https://freud.readthedocs.io/en/latest/modules/diffraction.html#freud.diffraction.DiffractionPattern).

**Comment by zhangyemayapro** [comment]
Thanks for your help~ There is no bug report, I placed the picture in the wrong space.
If I set the square box, the diffraction pattern will have 4-fold symmertry in small `k`, which is also irrational.

```
uc = freud.data.UnitCell.hex()
n_repeats = (20, 20,1)
system = uc.generate_system(n_repeats)
position=system[1]
position=position[np.linalg.norm(position,axis=1)<10]
box=np.array([20.,20.,  0.,  0.,  0.,  0.], dtype="float32")
system=(box,position)

sf=freud.diffraction.DiffractionPattern(grid_size=512)
sf.compute(system,peak_width=1,zoom=8)
```
![image](https://user-images.githubusercontent.com/32811826/228410001-2a600649-11c0-4980-a092-22b5de35043f.png)

**Comment by tommy-waltmann** [comment]
@zhangyemayapro please use a cubic box with 3 dimensions and particles in the x-y plane when computing the diffraction pattern for a 2 dimensional system. Versions of freud>=2.9.0 throw an exception when the box is not cubic, please upgrade your version of freud to see this behavior.

**Comment by zhangyemayapro** [comment]
Thanks for your help, I've update the freud and set cubic box, but the diffraction pattern still has 4-fold symmetry.
`box = np.array([20., 20.,  20,  0.,  0.,  0.], dtype="float32")`

![image](https://user-images.githubusercontent.com/32811826/228714876-7567fb3a-ffb5-4554-ac66-731e9d04e602.png)

**Comment by tommy-waltmann** [comment]
Attached below on the left is the diffraction pattern, on the right is the diffraction pattern after being rotated 90 degrees. They do not look the same, even at low k, so the pattern does not have 4-fold symmetry. If you think it has 4-fold symmetry, please explain further.

![diffraction_pattterns](https://user-images.githubusercontent.com/53307607/228866026-6b88a8d1-157f-480b-8a5b-bf9390d16cfd.png)

**Comment by zhangyemayapro** [comment]
Thanks for your help. I mean the center of the picture has a 4-fold symmetry.
![image](https://user-images.githubusercontent.com/32811826/230750450-4397dd30-348e-427d-b4e4-1cfcf540e6a8.png)

 And I realized that it is caused by when doing discrete Fourier Transform, the $dk=\pi/(L_{box})$.

![image](https://user-images.githubusercontent.com/32811826/230750386-16b3bf56-44eb-4ea2-8ecf-eb7925ae90d9.png)
