### ISSUE TITLE
Voronoi nlist seems to deallocate if voronoi object is garbage collected

### ISSUE THREAD

**Issue by b-butler** [glotzerlab/freud#1095]
### Description

When computing a neighbor list using `freud.locality.Voronoi`, if the Voronoi object is garbage collected but the neighbor list is not, accessing the properties of the neighbor list results in a segmentation fault.

This happens for multiple Python versions as well, though I report the one used for the minimal working example below.

I can fix this, but it may be some time before I get to it, since there is a simple work around of just storing the Voronoi object.

### Steps to Reproduce

```python
import freud
import numpy as np

N_replica = 6
system = freud.data.UnitCell.sc().generate_system(N_replica)

def get_voronoi(system):
    voronoi = freud.locality.Voronoi()
    voronoi.compute(system)
    return voronoi.nlist

nlist = get_voronoi(system)
nlist.neighbor_counts
```

### Error Output

```shell
No error output just a segmentation fault.
```

### freud Version

v2.12.1

### Python Version

v3.10.6

### System Platform

Linux

### Installation method

built from source

### Developer

None

**Comment by tommy-waltmann** [comment]
Thanks for reporting this! I'll have a look at it. The fix will likely be simple: make a deep copy of the neighborlist instead of a shallow one.
