### ISSUE TITLE
Support Cython 3.0

### ISSUE THREAD

**Issue by joaander** [glotzerlab/freud#1130]
### Description

Test and validate freud with Cython 3.0.

### Motivation and Context

Recent builds of `glotzerlab-software` with Cython 3.0 failed: https://github.com/glotzerlab/software/actions/runs/5579025927/jobs/10194017960?pr=311#step:5:6018

I assume this failure is due to the Cython 3.0 bump.

**Comment by tommy-waltmann** [comment]
After playing around a bit with this locally, it appears that cython 3 will introduce other problems too. Specifically the changes introduced in #1096 now lead to segmentation faults on intel macs and there are other problems on linux systems not included in the error output linked above.
