### ISSUE TITLE
Consistent usage of variable names

### ISSUE THREAD

**Issue by bdice** [glotzerlab/freud#180]
The code base need some consistency with respect to certain common variable names and docstring descriptions. The one that triggered this is `rmax` vs `r_max`, but there may be others. We should fix this for 2.0.

Current list of things we should document consistently:

* rmax, r_max
* rcut, r_cut
* neighborlist
* box

**Comment by vyasr** [comment]
Part of #179

**Comment by vyasr** [comment]
These conventions also need to be documented in the developer documentation.

**Comment by vyasr** [comment]
Done in #499.
