### ISSUE TITLE
setup.py re-compiles files unnecessarily

### ISSUE THREAD

**Issue by bdice** [glotzerlab/freud#191]
**[Original report](https://bitbucket.org/glotzer/freud/issue/191) by Jens Glaser (Bitbucket: [jens_glaser](https://bitbucket.org/jens_glaser), GitHub: Unknown).**

----------------------------------------

I notice a lot of duplicate g++ compile commands with setup.py:

```
building 'freud.bond' extension
gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -g -Iextern -I/opt/packages/python/Python-3.5.2-icc-mkl/lib/python3.5/site-packages/numpy-1.12.0b1-py3.5-linux-x86_64.egg/numpy/core/include -Icpp/bond -Icpp/box -Icpp/cluster -Icpp/density -Icpp/environment -Icpp/locality -Icpp/order -Icpp/parallel -Icpp/pmft -Icpp/registration -Icpp/util -I/opt/packages/python/Python-3.5.2-icc-mkl/include -I/opt/packages/python/Python-3.5.2-icc-mkl/include/python3.5m -c cpp/locality/NearestNeighbors.cc -o build/temp.linux-x86_64-3.5/cpp/locality/NearestNeighbors.o -std=c++11
...
building 'freud.box' extension
gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -g -Iextern -I/opt/packages/python/Python-3.5.2-icc-mkl/lib/python3.5/site-packages/numpy-1.12.0b1-py3.5-linux-x86_64.egg/numpy/core/include -Icpp/bond -Icpp/box -Icpp/cluster -Icpp/density -Icpp/environment -Icpp/locality -Icpp/order -Icpp/parallel -Icpp/pmft -Icpp/registration -Icpp/util -I/opt/packages/python/Python-3.5.2-icc-mkl/include -I/opt/packages/python/Python-3.5.2-icc-mkl/include/python3.5m -c cpp/locality/NearestNeighbors.cc -o build/temp.linux-x86_64-3.5/cpp/locality/NearestNeighbors.o -std=c++11
...
and so on...
```

latest master

**Comment by bdice** [comment]
**Original comment by Matthew Spellings (Bitbucket: [mspells](https://bitbucket.org/mspells), GitHub: [klarh](https://github.com/klarh)).**

----------------------------------------

It looks like distutils doesn't reuse `.o` files on purpose, see https://bugs.python.org/issue5372 . If speed is a concern, using ccache is an option, I suppose...

**Comment by bdice** [comment]
**Original comment by Jens Glaser (Bitbucket: [jens_glaser](https://bitbucket.org/jens_glaser), GitHub: Unknown).**

----------------------------------------

or just move common objects into a common.so

**Comment by vyasr** [comment]
Partly addressed by #292. Is there any more that we can do to improve the build time? Part of the reason it was less painful before is that build parallelism is supported out of the box by Unix Makefiles, whereas the setuptools support is buggy and very system-dependent.

**Comment by bdice** [comment]
I believe I've addressed all that we can do in terms of not compiling files that aren't strictly necessary for each module via #292. The next thing I would try would be to build the box/locality modules as shared objects and use those for all other modules. Alternatively, we could force `setup.py` to build the box and locality modules first, which would resolve the parallel dependencies and make compiling in parallel always safe (I think).

**Comment by bdice** [comment]
I investigated the suggestions I made above - I don't see how to further improve this at the current moment unless we adopt a different build system entirely.
