### ISSUE TITLE
Use atleast_2d everywhere

### ISSUE THREAD

**Issue by bdice** [glotzerlab/freud#199]
We should make sure that 1d inputs (single points) are allowed for analysis methods in freud.

**Comment by vyasr** [comment]
This should be done in conjunction with #268

**Comment by bdice** [comment]
@vyasr I talked with @jinsoo960 about this, we're not sure if we want to make a change for this in `convert_array` after all. We may just keep the call to `atleast_2d` before calling `convert_array` in the cases where we explicitly want this behavior. Otherwise it may confuse users and/or give unexpected answers by accepting inputs of the wrong dimensionality.

**Comment by vyasr** [comment]
For the box functions, here's code for a decorator that should do what we want:
```
def support_1d(func):
    def wrapper(self, arg1, *args, **kwargs):
        if len(arg1.shape) == 1:
            flat = True
            arg1 = np.atleast_2d(arg1)
        else:
            flat = False
        ret = func(arg1, *args, **kwargs)
        if flat:
            return ret.squeeze()
        else:
            return ret
```
