### ISSUE TITLE
Allow users to pass in angles or quaternions to 2D calculations

### ISSUE THREAD

**Issue by bdice** [glotzerlab/freud#200]
A wrapper should handle conversion. We might want to write it as a C library.

**Comment by vyasr** [comment]
Part of #179

**Comment by vyasr** [comment]
@bdice are you still thinking this is something we should do in C++? Or is this just a Python API enhancement? Accomplishing this in C++ would require some API overloading so I'd prefer not to bother.

Assuming you're fine with doing this on the Python side, at some point in the future we'll need to decide how the APIs in C++ should look (everything accepting quaternions or using angles for 2D or overloading functions to support both). I'm fine postponing that decision, though.

**Comment by bdice** [comment]
I think this should be a Python side change. I agree that standardization on the C++ side would be good -- I'm fine with choosing either quaternions everywhere for 2D angles, or scalar radians. Overloading for both is not needed.

**Comment by vyasr** [comment]
Resolved by #482.
