### ISSUE TITLE
Parallelize LocalQl, LocalWl, SolLiq

### ISSUE THREAD

**Issue by bdice** [glotzerlab/freud#207]
The computations for a few order parameters need to be parallelized by using Intel TBB in the C++ compute functions. This should be relatively straightforward, using the examples present in various other modules (e.g. density, PMFT).

**Comment by bdice** [comment]
@jekw90 Thanks for picking this issue! It's currently in progress in pull request #215, but there is some rewriting that needs to happen. To prepare for Friday, it would be great if you familiarized yourself with the differences between `LocalQl.compute`, `LocalQl.computeAve`, `LocalQl.computeNorm`, `LocalQl.computeAveNorm`, and the corresponding `LocalWl` compute methods.

First, I would read the summary of the methods on the documentation: https://freud.readthedocs.io/en/stable/order.html#freud.order.LocalQl

Next, I would read the C++ code file for `LocalQl.cc`. It's okay if you don't understand it yet, just make a list of your questions and we can discuss together. https://github.com/glotzerlab/freud/blob/master/cpp/order/LocalQl.cc

**Comment by jekw90** [comment]
Bradley Thank you. I will read the summary of methods. I will try to read the c++ code files. Are the c++ files in  the cpp/order directory ? 

Best regards,
Kwang

**Comment by bdice** [comment]
@jekw90 Yes, the files are in that directory. 👍

**Comment by bdice** [comment]
This is mostly covered by #247. A larger refactoring is being done in #242.
