### ISSUE TITLE
Export citations

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/freud#214]
Some of freud's methods are quite novel and are developed in other papers. We should make it easy to export citations for the relevant papers when a given method is being used. Most of the relevant citations should already exist in the freud documentation.

**Comment by bdice** [comment]
Some packages implement a root-level `__citation__` attribute which will be appropriate to add when we have a published paper on _freud_. https://github.com/adrn/CitationPEP

**Comment by bdice** [comment]
Solid Liquid order parameter: https://aip.scitation.org/doi/10.1063/1.471721

**Comment by vyasr** [comment]
Resolved by #383
