### ISSUE TITLE
Box constructor should allow single specifier

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/freud#217]
Cubic (square) boxes are an important enough use-case that `freud.box.Box(10)` or `freud.box.Box(L=10)` should be supported. I would say default is to use 3D unless is2D is set.

**Comment by klarh** [comment]
Isn't that what `freud.box.Box.cube` is for?

**Comment by vyasr** [comment]
It is, but as a user my first instinct for a cubic box is to just use the API I proposed above. When I'm prototyping code I tend to write the above, have my code fail, then remind myself that cube exists. I think there's no harm in supporting both ways, but this feels more natural to me and is the behavior I think most users would expect (especially HOOMD users).

**Comment by klarh** [comment]
The box constructor used to try to be clever, but it turned into a maintenance nightmare that ended up breaking someone's scripts somewhere every time a new corner case was "fixed." I would vote against this just based on that history. It's also an "analysis smell" in my opinion that I wouldn't mind discouraging a bit; I think the community deals with cubic boxes often, but far from exclusively.

**Comment by bdice** [comment]
I agree with @klarh - I vote `wontfix` for this issue. Closing for now.
