### ISSUE TITLE
Improving doc on source installation 

### ISSUE THREAD

**Issue by amayank-umich** [glotzerlab/freud#228]
**Describe the bug**
Documentation on using the flag --TBB-ROOT does not specify clearly what path of directory to use, which can be confusing at times. For example, I was using --TBB-ROOT /opt/local/include/tbb whereas --TBB-ROOT /opt/local should have be used

**Way to improve**
The doc for the flag --TBB-ROOT may be improved in the following way

**--TBB-ROOT**
The root directory where TBB is installed. For example, if the tbb.h is present in the directory `/opt/local/include/tbb/`, then `--TBB-ROOT /opt/local` should be used. Useful if TBB is installed in a non-standard location or cannot be located by Python for some other reason. Note that this information can also be provided using the environment variable TBB_ROOT. The options –TBB-INCLUDE and –TBB-LINK will take precedence over –TBB-ROOT if both are specified.

**Comment by vyasr** [comment]
Resolved in #476.
