### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by j-proc** [glotzerlab/freud#237]
### Problem
In evaluating the performance of freud, a particular focus in HPC workflows. A baseline is needed to observe how modifications to parts of the code effect the performance of the whole. Current testing ensures that modifications do not break functionality, however, performance changes are currently left to be evaluated by the contributor, PR reviewer, or after the fact when performance degradation is noticed by users.

### Proposed Solution
Generating performance metrics using standard python tools like cProfile and timeit. The results should be human readable in a terminal output and (optionally) saved in a file which makes comparison between versions trivial.

### Alternatives
Utilizing [perf](https://perf.readthedocs.io/en/latest/) instead of using default python modules and simply make it a requirement to run the benchmarking command. 

**Additional context**
This issue was generated following a discussion here https://github.com/glotzerlab/pythia/issues/2

**Comment by csadorf** [comment]
Ideally these tests are executed as part of the CI.

**Comment by vyasr** [comment]
Addressed by #279
