### ISSUE TITLE
Binary pypi package fails due to numpy linkage on google colab

### ISSUE THREAD

**Issue by klarh** [glotzerlab/freud#243]
**Describe the bug**
Google colab supports installing packages straight from pypi into a notebook's environment using pip. However, the numpy bundled with their container setup seems to be incompatible with the way freud's binary package was built for pypi. I haven't been paying too much close attention to how we're building binaries for pypi, but if it's not inconvenient, it may be useful to have them support whatever is special about this environment out of the box.

**To Reproduce**
1. Install freud in a colab notebook: `!pip install freud-analysis`
2. Import freud

**Error output**
`ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject`

**System configuration (please complete the following information):**
 - OS: linux
 - Version of Python: 3.6
- Version of freud: 1.0
- Version of numpy: 1.14.6

**Additional context**
An example notebook is located [here](https://colab.research.google.com/drive/1-2E6sVXAKxKnRsrUV_GoPbjrj0CfcKEr)

**Comment by bdice** [comment]
@klarh We're definitely seeing this on our personal systems, but I believe the issue I've seen was with conda-forge builds. @k-l-wang can you comment with a description of your related issue?

I don't know how to solve this at the moment. @vyasr we should try to reproduce this and figure out how to build it better.

**Comment by klarh** [comment]
FWIW, the binary versions seem to work on my local box with (non-conda) python 3.7.2 and both numpy 1.16.1 (from arch repository) and numpy 1.16.2 (binary version available on pypi).

**Comment by vyasr** [comment]
I presume that is due to the wheels being built against NumPy 1.16 during the CI builds that upload to PyPI. The CircleCI script looks at the requirements.txt file to find requirements, but that file does not specify anything about versions, so it probably pulls the most recent NumPy on PyPI and builds against that. If we force it to build against NumPy 1.10 (the oldest NumPy that we claim to support) then this problem should go away.

**Comment by klywang** [comment]
**Describe the bug**
(a) Updating freud < 1.0 to freud 1.0 in a conda environment corrupts the numpy installation. Downgrading freud to a version < 1.0 or reinstalling numpy using `pip install numpy -I` resolves the issue.

(b1) If the environment has already has pypi's numpy installed, freud installs with a separate "numpy-base" package. In some instances, `pip install numpy -I` could not fix this issue, and it could only be resolved by reinstalling numpy-base and all packages dependent on numpy/numpy-base with the updated version of freud. Downgrading from freud=1.0 to freud=0.11.4, then upgrading back to freud=1.0 results in the error again. I wasn't able to reproduce this error in any of my environments.

(b2) When I tried to reproduce (b1), `pip install numpy -I` resolved any issues.

**To reproduce**
For issue (a):
1. Create the conda environment with an earlier version of freud (freud < 1.0)
`conda create -n test freud=0.11.4`

2. Update freud
`conda update freud`

3. Import freud

For issue (b):
1. Create conda environment with numpy from the default channel:
`conda create -n test -c default numpy`
`conda install freud=0.11.4`
2. Update freud
`conda update freud`

3. Import freud

**Error output**
For issue:
```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/env/lib/python3.7/site-packages/freud/__init__.py", line 5, in <module>
    from . import box
  File "__init__.pxd", line 206, in init freud.box
  File "/path/to/env/lib/python3.7/site-packages/numpy/__init__.py", line 140, in <module>
    from . import _distributor_init
ImportError: cannot import name '_distributor_init' from 'numpy' (/path/to/env/lib/python3.7/site-packages/numpy/__init__.py)```

**System configuration**
* OS: Linux and Mac
* Version of Python: 3.7
* Version of freud: 1.0
* Version of numpy: 1.16.2

**Comment by vyasr** [comment]
@klarh's original issue has been resolved, I tested a notebook with the new PyPI wheels and they work. @klywang reported unrelated issues, @bdice you may want to take a look at how the conda pinning is affected by packages (pre-)installed via pip.

**Comment by vyasr** [comment]
Based on [this post](https://stackoverflow.com/questions/55048364/numpy-importerror-cannot-import-name-distributor-init), the issue that arises in the conda scenarios is due to conflicting numpy installations and the best solution is just to uninstall and reinstall numpy, as Kelly suggested.
