### ISSUE TITLE
Setting/getting number of threads should follow a "property" API

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/freud#285]
**Is your feature request related to a problem? Please describe.**
It should be possible to access the number of threads currently in use.

It would also be nice to be able to set the number of threads in a more Pythonic fashion.

**Describe the solution you'd like**
I'm not sure how we can accomplish this off the path; if it requires too much hacking, then we can just convert the existing private variable to a public one. But it would be very Pythonic to be able to do `freud.parallel.threads=5` or so.

**Describe alternatives you've considered**
I don't know how to get around the fact that setting a module attribute like I suggested above will just overwrite the object. There's not really a concept of module-level properties AFAIK. If there was, that would be the solution I would advocate.

**Comment by bdice** [comment]
I tried to do this in #298. I looked into alternatives and struggled to come up with anything better. I think the only choice would be to create a class `parallel` and fake it as if that were the module, keeping the same API as before. But we'd have to [implement a class property](https://stackoverflow.com/questions/128573/using-property-on-classmethods)... not worth the increased complexity in my opinion.
