### ISSUE TITLE
Fix docstrings referring to N_particles

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/freud#310]
The docs currently have a random mix of terminology for the number of points. This issue is especially convoluted because ref_points need not coincide with points.

We should standardize the terminology around this and update all docstrings in freud to match. This is related to #179, and also somewhat to #180.

**Comment by vyasr** [comment]
I'm actually not 100% sure what to do with this. We've updated the majority of the APIs, and in particular removing the `num_particles` properties from most things has made this much easier. However, I'm not sure if we should update all the docstrings; some methods really are about particles. For example, does it make sense to change things in `environment` like `BondOrder` or `LocalDescriptors` to just discuss `points` in the docstrings? I'm not sure what the answer is, would like to discuss a bit more before deciding.

**Comment by bdice** [comment]
Docstrings are pretty good now. Closing as unnecessary.
