### ISSUE TITLE
Add more plottable analyses

### ISSUE THREAD

**Issue by bdice** [glotzerlab/freud#314]
There are a couple compute classes whose results can be easily visualized that were not handled in #302. I suggest the following:

- [GaussianDensity in 2D systems](https://freud.readthedocs.io/en/stable/examples/module_intros/Density-GaussianDensity.html) - use real X and Y coordinates, and check what happens if the 2D box is sheared.
- [LocalQl (and its variants) as a histogram](https://freud.readthedocs.io/en/stable/examples/module_intros/Order-Steinhardt.html) - let the X axis be automatically determined by the data

**Comment by bdice** [comment]
(Congrats on our 100π<sup>th</sup> issue)

**Comment by jinsooihm** [comment]
What would you like the colorbar label, title, for GaussianDensity to be?
<img width="616" alt="Screen Shot 2019-06-19 at 2 53 37 PM" src="https://user-images.githubusercontent.com/15791520/59792402-1703e800-92a2-11e9-8e26-0e68006289c4.png">
<img width="577" alt="Screen Shot 2019-06-19 at 2 53 29 PM" src="https://user-images.githubusercontent.com/15791520/59792403-1703e800-92a2-11e9-8fff-6c5390581f9e.png">

**Comment by bdice** [comment]
@jinsoo960 Axis labels should be _x_ and _y_. Colorbar and titles are fine as shown in that screenshot.

**Comment by jinsooihm** [comment]
<img width="618" alt="Screen Shot 2019-06-19 at 5 17 31 PM" src="https://user-images.githubusercontent.com/15791520/59801296-52101680-92b6-11e9-8929-b7439a8452fa.png">
<img width="609" alt="Screen Shot 2019-06-19 at 5 17 26 PM" src="https://user-images.githubusercontent.com/15791520/59801299-52101680-92b6-11e9-8afb-8f946e81cf21.png">
<img width="637" alt="Screen Shot 2019-06-19 at 5 17 19 PM" src="https://user-images.githubusercontent.com/15791520/59801306-52a8ad00-92b6-11e9-8c84-10d2ff1ab925.png">
<img width="603" alt="Screen Shot 2019-06-19 at 5 17 06 PM" src="https://user-images.githubusercontent.com/15791520/59801307-52a8ad00-92b6-11e9-9ae6-65329276ef69.png">
These are the histograms on random points.
