### ISSUE TITLE
Gaussian Density for Sheared Boxes

### ISSUE THREAD

**Issue by bdice** [glotzerlab/freud#319]
While working with @jinsoo960 on #314 and #318, I noticed that the Gaussian Density module doesn't work as I had expected in sheared boxes. I'm not convinced that the current behavior for sheared boxes is useful.

I expected that the coordinate system used by the discretization into bins would account for the sheared nature of the box, as if it had computed the bin centers in fractional coordinates. This does not appear to be the case.

I expected something that looks like like this, after shearing the image (shearing direction might be backwards - I made this with Photoshop):
![image](https://user-images.githubusercontent.com/3943761/59803981-1f1c5180-92bb-11e9-82e5-2f4bf513d457.png)

When naively calling `imshow` on the output, we get this:
![image](https://user-images.githubusercontent.com/3943761/59804018-3bb88980-92bb-11e9-9e33-ad7e73436705.png)

This indicates to me that the "pixelization" of the Gaussian Density module isn't using "sheared pixels," and just assumes the box is orthorhombic.

Code to generate:

```python
r_max = 2
N = 1000
L = 10  # Box length
box = freud.box.Box.square(L)
centers = np.array([[L/4, L/4, 0],
                    [-L/4, L/4, 0],
                    [L/4, -L/4, 0],
                    [-L/4, -L/4, 0]])

# (box, positions) = make_fcc(4, 4, 4)
points = []
for center in centers:
    points.append(np.random.multivariate_normal(center, cov=np.eye(3, 3), size=(int(N/4),)))
points = box.wrap(np.concatenate(points))
points[:, 2] = 0
```

**Comment by bdice** [comment]
Update: My intuition may have been wrong. I thought about this some more and I think the current implementation makes much more sense (with square pixels/voxels instead of shearing with the box) if users plan to take the Fourier Transform of the resulting Gaussian Density in order to calculate diffraction patterns (#245).

**Comment by vyasr** [comment]
I'm not sure that this is an issue either. @bdice I'd vote to close this unless you still want to change the behavior.
