### ISSUE TITLE
make_default_nlist not working as the documentation.

### ISSUE THREAD

**Issue by jinsooihm** [glotzerlab/freud#320]
**Describe the bug**
`freud.locality.make_default_nlist` does not work as the documentation for the `exclude_ii` option.
The docstring says if `exclude_ii=None`, then it should be considered `True` if `ref_points` and `points` are the same object.
But it seems like that `None` is considered as `False` regardless of `points` and `ref_points` being the same object or not.

**To Reproduce**
<img width="763" alt="Screen Shot 2019-06-20 at 2 21 17 PM" src="https://user-images.githubusercontent.com/15791520/59871940-b38fbe00-9366-11e9-930f-ba6c05fdab45.png">

**System configuration (please complete the following information):**
 - Version of Python: 3.6.8
 - Version of freud: 1.1.0

Without this properly implemented, it seems like the C++ internal checks for same points (for example, by checking distance < 1e-6) cannot be removed.

**Comment by vyasr** [comment]
I think we should probably fix this in master, not wait until `next`. The C++ checks will become redundant, but I don't think every class does this correctly right now in C++ anyway, so making this behave as documented is probably the right approach @jinsoo960.

**Comment by vyasr** [comment]
No longer really relevant, but any outstanding ambiguity was resolved by #452
