### ISSUE TITLE
Steinhardt Wl parameters are computed incorrectly

### ISSUE THREAD

**Issue by bdice** [glotzerlab/freud#369]
**Describe the bug**
I expected that the results from the Wl order parameter would be rotationally invariant. It doesn't seem like the result I get are what I expect.

**To Reproduce**
1. Start with a single particle at the origin surrounded by 12 neighbors in an FCC arrangement.
2. Create a `Steinhardt` or `LocalWl` object with a manually-constructed neighborlist.
3. Compute the order parameters. The real part of W6 for the particle at the origin is -0.00262604 for Steinhardt, LocalWl, and pyboo.
4. Rotate the points around the origin and compute the order parameters again.
5. Results disagree with those of `pyboo`. The results from freud appear to be different after the rotation.

```python
import rowan
import freud
import numpy as np
import boo

box = freud.box.Box.cube(10)
positions = np.array([[0, 0, 0],
                      [-1, -1, 0],
                      [-1, 1, 0],
                      [1, -1, 0],
                      [1, 1, 0],
                      [-1, 0, -1],
                      [-1, 0, 1],
                      [1, 0, -1],
                      [1, 0, 1],
                      [0, -1, -1],
                      [0, -1, 1],
                      [0, 1, -1],
                      [0, 1, 1]])
index_i = np.zeros(12)
index_j = np.arange(1, 13)
nlist = freud.locality.NeighborList.from_arrays(13, 13, index_i, index_j)
nlist.distances[:] = np.sqrt(2)
ql = freud.order.Steinhardt(r_max=1.5, l=6, Wl=True)
lwl = freud.order.LocalWl(box, 1.5, 6)

print('FCC:')
ql.compute(box, positions, nlist=nlist)
print('Steinhardt:', ql.order)
lwl.compute(positions, nlist=nlist)
print('LocalWl:', lwl.Wl)
q6m = boo.bonds2qlm(positions, nlist[:], l=6)
w6 = boo.wl(q6m)
print('pyboo:', w6)

# Again but rotated
quat = rowan.random.rand()
positions_rot = rowan.rotate(quat, positions)

print('\nROTATED FCC:')
ql.compute(box, positions_rot, nlist=nlist)
print('Steinhardt:', ql.order)
lwl.compute(positions_rot, nlist=nlist)
print('LocalWl:', lwl.Wl)
q6m = boo.bonds2qlm(positions_rot, nlist[:], l=6)
w6 = boo.wl(q6m)
print('pyboo:', w6)
```

**Error output**
```python
FCC:
Steinhardt: [-0.00262604-4.1720927e-10j         nan          +nanj
         nan          +nanj         nan          +nanj
         nan          +nanj         nan          +nanj
         nan          +nanj         nan          +nanj
         nan          +nanj         nan          +nanj
         nan          +nanj         nan          +nanj
         nan          +nanj]
LocalWl: [-0.00262604-4.1720927e-10j         nan          +nanj
         nan          +nanj         nan          +nanj
         nan          +nanj         nan          +nanj
         nan          +nanj         nan          +nanj
         nan          +nanj         nan          +nanj
         nan          +nanj         nan          +nanj
         nan          +nanj]
pyboo: [-0.00262604 -0.09791764 -0.09791764 -0.09791764 -0.09791764 -0.09791764
 -0.09791764 -0.09791764 -0.09791764 -0.09791764 -0.09791764 -0.09791764
 -0.09791764]

ROTATED FCC:
Steinhardt: [-0.00854041-0.00187109j         nan       +nanj         nan       +nanj
         nan       +nanj         nan       +nanj         nan       +nanj
         nan       +nanj         nan       +nanj         nan       +nanj
         nan       +nanj         nan       +nanj         nan       +nanj
         nan       +nanj]
LocalWl: [-0.00854041-0.00187108j         nan       +nanj         nan       +nanj
         nan       +nanj         nan       +nanj         nan       +nanj
         nan       +nanj         nan       +nanj         nan       +nanj
         nan       +nanj         nan       +nanj         nan       +nanj
         nan       +nanj]
pyboo: [-0.00262604 -0.09791764 -0.09791764 -0.09791764 -0.09791764 -0.09791764
 -0.09791764 -0.09791764 -0.09791764 -0.09791764 -0.09791764 -0.09791764
 -0.09791764]
```

**System configuration (please complete the following information):**
 - OS: Ubuntu
 - Version of Python: 3.7
 - Version of freud: `next`, commit 554290969eb998ecc21563ebac4bcefeaa0ddf2b

**Comment by klarh** [comment]
Do the Wl use clebsch-gordan coefficients? Simon recently found a bug in the pythia bispectrum descriptors ( https://github.com/glotzerlab/pythia/issues/9 ) making them not rotationally invariant because fsph does not use the condon-shortley phase convention, whereas the clebsch-gordan coefficients from sympy do.

**Comment by bdice** [comment]
@klarh The Wigner 3j coefficients are precomputed and stored here: https://github.com/glotzerlab/freud/blob/master/cpp/order/wigner3j.cc

The script used to generate these is shown here, and it uses `sympy`: https://github.com/glotzerlab/freud/blob/master/cpp/order/wigner3j.h

I'm not sure what to attribute this to yet. I think it's entirely possible that fsph and sympy disagree on conventions.

**Comment by bdice** [comment]
This discrepancy persists at least as far back as v0.8.2, the oldest version for which builds are available from conda-forge.

**Comment by klarh** [comment]
If you want to test whether this is the cause, the fix is just a matter of negating the m>0, odd m spherical harmonics (python version at https://github.com/glotzerlab/pythia/pull/10/files ) produced by fsph.

**Comment by bdice** [comment]
A preliminary test with multiplying Ylm by -1 for all positive, odd m doesn't seem to solve it.

**Comment by bdice** [comment]
I think I've found the main problem, which was indeed a sign convention problem, but slightly more complicated than expected. I will make a PR for this.

In comparing our results to pyboo, I am pretty convinced that the Wls are always supposed to be real-valued (we've been returning them as complex values but the imaginary part is just due to numerical imprecision from what I can tell). Our current code has nonzero imaginary parts because it's doing the wrong math.
