### ISSUE TITLE
RDF should use "bins" argument

### ISSUE THREAD

**Issue by bdice** [glotzerlab/freud#385]
The RDF and CorrelationFunction codes should allow a bin definition similar to `np.histogram`:

`bins : int or sequence of scalars or str, optional`

An argument name `bins` could be defined as "integer number of bins" for now and generalized to "or an array of bin edges" later.

_Originally suggested by @csadorf in https://github.com/glotzerlab/freud/issues/179#issuecomment-514261487_

**Comment by vyasr** [comment]
Resolved in #459
