### ISSUE TITLE
Convert README to reStructured Text

### ISSUE THREAD

**Issue by bdice** [glotzerlab/freud#392]
The README should be converted from Markdown to ReStructured Text.

A couple reasons:
- There's a quirky bug in the wheel uploading process on MacOS with Python 3.5, which vaguely resembles this: https://github.com/pypa/twine/issues/454#issuecomment-464055144
- Reduces duplication between the documentation index page and README

Steps:
1. Compare the README.md and index page of the docs to determine the differences in content.
2. Add content from README.md to the index page of the docs.
3. Move the index page of the docs (which is already in RST) to the root of the repo and remove the Markdown file.
4. Use `.. include` in the docs' index page, to have the README.rst content appear with the table of contents and such. The result will probably look something like this: https://raw.githubusercontent.com/TDAmeritrade/stumpy/master/docs/index.rst

**Comment by vyasr** [comment]
How strongly do you feel about actually merging the README and the index? The contents are actually quite different, and I think that's reasonable given that the doc index can just say go to the next page for "how to install" whereas the README has to point elsewhere. The Markdown->rst conversion is trivial, just deciding whether the combining with index is worthwhile.

**Comment by vyasr** [comment]
Resolved by #477
