### ISSUE TITLE
Add strict_cut filter to query arguments.

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/freud#393]
For nearest neighbor queries, it should be possible to set a flag similar to the current NearestNeighbors class that will not find any neighbors beyond a certain distance.

**Comment by bdice** [comment]
This should just be `r_max`, with a new implementation of the existing variable.

For nearest neighbor queries, the guessed distance should be held in `r_guess` or similar.

`r_guess` should default to a value derived from the computed system density.

**Comment by vyasr** [comment]
Resolved by #429.
