### ISSUE TITLE
Standardize query arguments

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/freud#394]
Currently we instantiate QueryArgs in compute/accumulate methods in Cython and pass them through to C++. Defaults are determined by whatever defaults are specified inside these compute methods. We should have a more well-defined resolution order where defaults are specified and used consistently.

The best approach will be to store a class attribute dictionary for all such classes that contains default query arguments. If users provide default values, they are used, but must be complete. We should provide some level of query mode inference, so that users could provide query arguments that contain just `r_max`, for example, and have that automatically be a ball query. We should keep the mode argument available to support any future query modes that might lead to conflicts with this resolution, see #372 for example.

**Comment by bdice** [comment]
This is fixed in #395 and subsequent PRs.
