### ISSUE TITLE
Cluster should support separate points and query_points

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/freud#399]
All other methods in freud support passing two distinct sets of points. This should also be possible for clustering.

**Comment by bdice** [comment]
@vyasr How do you envision this working? (Also Steinhardt, Voronoi, other methods do not accept two sets of points.)

**Comment by vyasr** [comment]
Actually after giving this some more thought, I agree that this is probably not sensible. I don't know think the problem statement is even well-defined in this case. I came across it during API redesign and made the issue, but don't think we need to pursue it.
