### ISSUE TITLE
Validate Minkowski Structure Metrics

### ISSUE THREAD

**Issue by bdice** [glotzerlab/freud#404]
Another implementation of Minkowski Structure Metrics is available here from @ArvDee: https://github.com/ArvDee/Minkowski-structure-metrics-calculator

This alternate implementation and the values referenced below should be used in validation tests of the freud library.

[Rein ten Wolde et al., J. Chem. Phys (1996)](http://aip.scitation.org/doi/10.1063/1.471721) reports values for the Steinhardt w4 and w6 in Table 1.
[Dietz et al., Phys. Rev. E (2016)](https://link.aps.org/doi/10.1103/PhysRevE.94.033207) report the Minkowski structure metric values q4' and q6' for a BCC lattice in section IIc.

_Originally from https://github.com/glotzerlab/freud/pull/367#issuecomment-523973188_

**Comment by vyasr** [comment]
@bdice @yzjin is this resolved by #460? I believe there's a bit of extra testing to be done to resolve why HCP and a few specific cases fail, is that the main outstanding work?

**Comment by vyasr** [comment]
@bdice was there ever any further work on this front?

**Comment by bdice** [comment]
@vyasr PR #460 added tests that succeed for almost all cases. Our answers disagreed with the references for HCP and a few other specific cases but looking into that is low priority for me. I think it's something pathological, perhaps caused by different assumptions or numerical imprecision or something like that. This issue can be closed, I think.
