### ISSUE TITLE
radius of gyration support for polymers

### ISSUE THREAD

**Issue by atravitz** [glotzerlab/freud#407]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Use cluster properties to compute radius of gyration for polymers (passed in as sets of particles?)

**Describe alternatives you've considered**
I've been brute-forcing this with numpy.

**Additional context**

**Comment by bdice** [comment]
This is a documentation problem -- we can already do this with `ClusterProperties`, and it might make sense to rename that class.

**Comment by vyasr** [comment]
#510 enables this, but we still probably need to address the naming issue.

**Comment by bdice** [comment]
Closing. It's not clear what other names would be better.
