### ISSUE TITLE
Unify neighbor querying methods for v2.0

### ISSUE THREAD

**Issue by bdice** [glotzerlab/freud#410]
To make the user experience more consistent between compute classes and NeighborQuery objects, I propose to alter the `query` method behavior (which current performs nearest-neighbor queries) to accept query arguments, e.g. `{'num_neighbors': 12}` and remove the `queryBall` method.

This makes the user experience clearer, since users would use query arguments in locality classes as well as all compute classes.

**Comment by bdice** [comment]
Move towards: `nq.query(**kwargs)` where `**kwargs` is a dictionary of query arguments like `r_max = 3.0`.

Also we should make `nlist` and `qargs` into one argument called `neighbors`, to be resolved at the Cython level.

**Comment by vyasr** [comment]
Resolved in #419.
