### ISSUE TITLE
Simplify neighbor finding logic in C++

### ISSUE THREAD

**Issue by bdice** [glotzerlab/freud#412]
@vyasr and @bdice need to review the C++ API to determine if parts can be simplified or made private, to prevent accidentally using the wrong methods. Also names should be clarified.

**Comment by bdice** [comment]
We should rewrite the `NeighborQueryIterator`s to only accept one point, and require a `query_point_id`. This will simplify the hacks around exclusion logic. In most cases, we already use only one point to enable parallelism.

**Comment by vyasr** [comment]
Resolved in #419.
