### ISSUE TITLE
RawPoints shouldn't make an AABBQuery unless needed by querySingle

### ISSUE THREAD

**Issue by bdice** [glotzerlab/freud#420]
An internally-held AABBQuery should not be made on construction of a RawPoints object, only if `querySingle` is called.

Maybe initialize `aq` as a null pointer. When `querySingle` is called, then construct the AABBQuery before querying if needed. Being parallel-safe may be tricky.

_Originally posted by @bdice in https://github.com/glotzerlab/freud/pull/419_

**Comment by vyasr** [comment]
Resolved by #489.
