### ISSUE TITLE
Improve developer docs

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/freud#433]
This issue will serve as a task list for proposals to improve the overall documentation of freud. Some of these changes have been initiated in #348, but we need to keep a thorough list to make sure nothing is missed.

- [x] Add a quickstart guide so that capable users can immediately start using freud.
- [x] Add a tutorial introducing how to use freud.
- [x] Add an overview of neighbor finding and pair computation, including valid argument signatures.
- [x] Add description of query arguments and which ones are valid in what context.
- [x] Explain freud boxes and how they work with respect to periodic boundary conditions.
- [ ] Separate developer specific topics into their own section.
- [x] Move API documentation into a specific section.
- [x] Add more examples focused on introducing the code, most existing examples are too science-oriented and explain the concepts behind the methods.
- [x] All documentation referring to "reference [points|orientations|particles|etc]" need to be updated.
- [x] As per #180, the standard variable names should be added to the developer documentation.

**Comment by bdice** [comment]
Developer documentation is still out of date and makes many recommendations that no longer fit with the design of freud. We will release v2.0 without making these documentation updates, but it would be a good future improvement.
