### ISSUE TITLE
Inline references

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/freud#435]
I think our references section is a little strange to be honest. I think we should put all citations inline (i.e. in the context of whatever method they're there for) and get rid of this section. We should also get more consistent with having citations, but that's a longer term things (maybe good for a hackathon to ask someone to identify features that need a citation).

_Originally posted by @vyasr in https://github.com/glotzerlab/freud/pull/383/files_

**Comment by bdice** [comment]
We should use this package: https://sphinxcontrib-bibtex.readthedocs.io/en/latest/quickstart.html#minimal-example

**Comment by vyasr** [comment]
After attempting this with #520 (where we did switch to bibtex), we decided that inlining citations was not worth the extra complications associated with avoiding duplicate references in bibtex.
