### ISSUE TITLE
hard to tell where import util is supposed to come from

### ISSUE THREAD

**Issue by jennyfothergill** [glotzerlab/freud#446]
**Describe the bug**
Following along with this demo
https://freud.readthedocs.io/en/stable/examples/module_intros/Density-LocalDensity.html
It has `import util`, and it's easy to think this means import freud.util. Anyway, it took me a bit to figure out that util is from https://github.com/glotzerlab/freud-examples

**To Reproduce**
n/a

**Error output**
n/a
**System configuration (please complete the following information):**
n/a
**Additional context**
Explaining where util is from or providing setup for the examples would help.

**Comment by jennyfothergill** [comment]
OK, the main examples page https://freud.readthedocs.io/en/stable/examples.html gives this information, but it might be easier for the user if all the information was on the page they're on.

**Comment by bdice** [comment]
@jennyfothergill Thanks for filing an issue! It's really helpful to know what is confusing for new users, so please keep us in the loop as you explore the library and its features. We've heard this feedback from others as well, so we're planning to remedy this in the near future. We're preparing for a 2.0 release, and will be updating our examples.

**Comment by bdice** [comment]
Related issue: #390.

**Comment by bdice** [comment]
Most functions have been added to `freud.data` or `freud.plot` as of PR #532. The corresponding PR to freud-examples includes other changes that should help address this. https://github.com/glotzerlab/freud-examples/pull/9
