### ISSUE TITLE
Calculate Bond, Angle, and Dihedral Distributions

### ISSUE THREAD

**Issue by mikemhenry** [glotzerlab/freud#447]
**Is your feature request related to a problem? Please describe.**
For an array of pairs/triplets/quadruplets of points I would like to calculate bond distance/angle/dihedral angle. It would be nice to average these values over multiple frames. 

**Describe the solution you'd like**
API that creates some object to evaluate these distributions, lets me accumulate across frames, and returns some histogram object that I can use to plot distributions.

**Describe alternatives you've considered**
I haven't found anything that works with numpy arrays, most packages also make assumptions about system (ewww assumes angstroms or nanometers)

**Additional context**
It would be nice for there to be some logic in handling minimum image conversions in case users don't have the image data, positions could still be unwrapped with the assumption that no bond will be more than L/2

**Comment by vyasr** [comment]
@mikemhenry did you have any further thoughts on what you'd want something like this to look like, or did you find applications? Offhand this doesn't seem complex enough to merit including in freud; can you not do this quickly enough with pure Python? The hardest part seems to me to be actually evaluating the angles based on PBCs, which I think would be something that we could include a few line Python recipe for somewhere in our docs. Of course it would require a little broadcasting, but that doesn't seem too bad to me; let me know if I'm missing anything though.

**Comment by mikemhenry** [comment]
You are correct @vyasr Angles are annoying since you may need to account for up to two particles in the "wrong" image and they need to be moved using the standard convention. Also since freud doesn't really have the concept of "bond" the user will still have to figure out the indices for each pair or triplet, and then at that point, most of the work is done.
