### ISSUE TITLE
Move forLoopWrapper to util file

### ISSUE THREAD

**Issue by bdice** [glotzerlab/freud#449]
The C++ function `forLoopWrapper` should be moved to a `util` file instead of in `locality/NeighborComputeFunctional.h`. Nothing about it is specific to `locality`, and it should replace the TBB loop structures for all of the compute classes in `environment` and elsewhere. It's really helpful when debugging and developing to be able to enable/disable parallelism with a flag. Also the `parallel` flag should have a default value (probably `true`).

**Comment by vyasr** [comment]
I'm working on a branch right now that moves the looping over `NeighborList` logic from `loopOverNeighbors` into a separate function. I'm creating that function precisely for looping in `environment` for methods that have to use a `NeighborList`, and I'm rewriting those methods appropriately. I'm not necessarily opposed to moving the `forLoopWrapper`, but I'm not sure yet if there are any use-cases where it should actually be used outside of `locality` in lieu of exposing the loops over NeighborLists.

**Comment by vyasr** [comment]
Actually I'm walking this back, there are multiple computes that are loops that are not loops over neighbors (for example, Cubatic loops over replicates and Nematic loops over just a list of orientations). Those could definitely benefit from the generic for loop that can be parallelized.

**Comment by vyasr** [comment]
This was done in #455.
