### ISSUE TITLE
Normalization of Steinhardt Order Parameter Wl

### ISSUE THREAD

**Issue by yzjin** [glotzerlab/freud#456]
**Is your feature request related to a problem? Please describe.**
I was trying to verify the computation of wl computed by freud with the values given from [this link]. (https://github.com/ArvDee/Minkowski-structure-metrics-calculator/tree/master/testLattices)
The current computation of Steinhart Wl Order parameter in ```freud.local.Steinhardt``` doesn't enable it to be normalized by the value over all particles.

**Describe the solution you'd like**
Add an option for Wl normalization.

**Comment by bdice** [comment]
This is the formula to implement:
![image](https://user-images.githubusercontent.com/3943761/65439666-8cc5a580-ddf5-11e9-8af1-0e1daea30e13.png)
Citation: https://aip.scitation.org/doi/abs/10.1063/1.1638740

**Comment by vyasr** [comment]
Resolved by #460.
