### ISSUE TITLE
Improve indexing outside of ManagedArray context

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/freud#457]
Alternatively make an indexing method that isn't `static`, using the shape of the instantiated object's underlying array?

_Originally posted by @bdice in https://github.com/glotzerlab/freud/pull/455_

**Comment by bdice** [comment]
Closing, not necessary. If we chose to implement this later, the code snippet would probably look something like this:
```c++
inline std::vector<size_t> getMultiIndex(size_t index)
{
    return ManagedArray::getMultiIndex(this->shape(), index);
}
```
