### ISSUE TITLE
Double precision

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/freud#464]
**Is your feature request related to a problem? Please describe.**
Some calculations (like Steinhardt order parameters) can be highly sensitive to small changes in specific cases (such as near-ideal crystals). In those cases, using double- rather than single-precision arithmetic would help. In addition most users working with numpy are creating double precision arrays by default, so there's a lot of unnecessary copying of data happening every time they use freud.

**Describe the solution you'd like**
We should define a simple `Scalar` typedef in `VectorMath` or `HOOMDMath` that can be used everywhere in place of float. We would then add a preprocessor flag that allows us to decide whether to compile in single or double precision. We would also need to create a function exposed to Python so that our Cython code in common.pyx can determine what NumPy types to use for its arrays.

**Describe alternatives you've considered**
If this ends up being too much of a pain, we could just make freud a double precision library always. There would be performance implications but in general I'd expect it to be different by a factor of two or so in any case.

**Comment by joaander** [comment]
The original motivation for single precision is that file formats like DCD and GSD store values in single precision. Thus a single-precision freud *avoids* the need to make copies and convert data types in those use-cases. Yes, data inputs passed from default-constructed numpy-arrays are double - but users can be taught to specify `dtype=numpy.float32` where performance matters.

For the use-case you mention, what is the instability? Do the particle coordinates really need to be in double? Or is it just one particular step in the Steinhardt calculation (i.e. the computation and/or averaging of spherical harmonics)? If the latter, one option is to use doubles where they are necessary in intermediate calculations but still accept inputs as floats.

Preprocessor directives don't work well with pip/conda packages. To enable full single and full double selectable at run time, consider instead templating all operations on Real and instantiate them with both single and double. 

As you say, all this is contingent on how much performance loss there is by switching to full double. We should evaluate that quantitatively to inform the path forward. We should include a measurement of the performance overhead of converting float input to doubles to simulate the performance loss when performing interactive analysis on gsd trajectories.

**Comment by vyasr** [comment]
While I still think this feature would be nice, at the moment freud is explicitly using double precision wherever necessary and that seems good enough. We can revisit this if someone starts finding significant issues in the future, but since we're not doing anything that requires e.g. strict conserved quantities I don't think this is critical.
