### ISSUE TITLE
Voronoi beta

### ISSUE THREAD

**Issue by syjlee** [glotzerlab/freud#506]
1. Wrapping position for plotting: positions of Voronoi vertices are not matched with the whole box.
![position_wrapping](https://user-images.githubusercontent.com/44685431/66155777-5efb1080-e5ee-11e9-97d4-56baff7fdf61.png)

2. Wrong ordering of vertices gives a 2D plot of patches with inner lines.
![current_voronoi_plot](https://user-images.githubusercontent.com/44685431/66155962-bbf6c680-e5ee-11e9-8c14-3f46700ed17a.png)

3. The doc for Voronoi needs to be updated including adding in overview.

**Comment by vyasr** [comment]
Resolved by #507
