### ISSUE TITLE
Import freud fails when installed with pip

### ISSUE THREAD

**Issue by lyrivera** [glotzerlab/freud#543]
**Describe the bug**

Installing `freud` with `pip` results on the following error when importing:

**Error output**
```bash
$ pip install freud-analysis --user
Collecting freud-analysis
  Using cached https://files.pythonhosted.org/packages/c3/82/47f1ab30279662ef542d445e5c7451cec095dda568aa7305fab4b31ef739/freud_analysis-2.0.0-cp37-cp37m-macosx_10_12_x86_64.whl
Requirement already satisfied: numpy>=1.10 in /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from freud-analysis) (1.17.2)
Requirement already satisfied: rowan>=1.2 in ./Library/Python/3.7/lib/python/site-packages/rowan-1.2.0-py3.7.egg (from freud-analysis) (1.2.0)
Installing collected packages: freud-analysis
Successfully installed freud-analysis-2.0.0
$ python
Python 3.7.5 (default, Oct 28 2019, 07:13:20)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import freud
Fatal Python error: PyThreadState_Get: no current thread
Abort trap: 6
```

**System configuration (please complete the following information):**
 - OS: macOS Catalina (10.15)
 - Version of Python: v3.7.5
 - Version of freud: v2.0

**Comment by vyasr** [comment]
Do you have tbb installed? If not, could you try installing it and see if you can import freud after that? You shouldn't have to, but this is almost certainly a linking issue and tbb is the only obvious culprit.

**Comment by bdice** [comment]
This reminds me of an issue that happened with freud v0.6 where builds created for Python 3.x.z would not work with 3.x.y for y < z. That is, maybe we built against too new of a bugfix release. I bumped the bugfix versions we built against because I thought it was a good idea...

@lyrivera Try using the newest bugfix release of your Python version and see if that helps.

**Comment by lyrivera** [comment]
Turns out I hadn't realize that there was an older version of freud (built from source) in my `PYTHONPATH`. Once removed, I can import the pip installed version without problems. Closing this now. Thanks.

**Comment by bdice** [comment]
@lyrivera Thanks for letting us know! That's a huge relief.
