### ISSUE TITLE
Querying link 404s

### ISSUE THREAD

**Issue by mikemhenry** [glotzerlab/freud#559]
**Describe the bug**
On this page of the docs:
https://freud.readthedocs.io/en/stable/modules/locality.html#freud.locality.LinkCell.query
The link to the quarry API 404s:
https://freud.readthedocs.io/en/stable/querying.html
The link should be:
https://freud.readthedocs.io/en/stable/topics/querying.html

I will submit a PR to fix this.

**Comment by bdice** [comment]
@mikemhenry Thanks! This probably appears a few times. `grep` is your friend. (Though we both know you love ripgrep 😉)

**Comment by mikemhenry** [comment]
Do we want everything to point to stable?

For example in `freud/pmft.pyx`, should `https://freud.readthedocs.io/en/next/querying.html` get turned into `https://freud.readthedocs.io/en/stable/topics/querying.html` or `https://freud.readthedocs.io/en/next/topics/querying.html`

This pull request is sponsored by `rg --replace` :)

**Comment by bdice** [comment]
Yes, `next` was our dev branch for v2 and everything should now point to `stable`.

**Comment by bdice** [comment]
@mikemhenry FYI, we don't do this with rST cross-references because it becomes useless when people use the docs from `help(...)` or other places outside of Sphinx-generated docs. Thus hard-coded https links are our preference here and in signac.
