### ISSUE TITLE
Improve Query Arguments: Mode documentation

### ISSUE THREAD

**Issue by mikemhenry** [glotzerlab/freud#563]
Discussed on the mailing list:

> To clarify: a 'ball' query means "find me all neighbors within a certain radius", whereas a 'nearest' query means "find me the closest x neighbors". You assume correctly that setting `mode='none'` (or None) tells freud to deduce the mode based on the other arguments. The argument deduction is actually pretty simple: if a 'num_neighbors' is specified it assumes that you want to find exactly that many neighbors for every point. You have to always specify at least one of 'num_neighbors' and 'r_max'. If you only specify 'r_max', then freud performs a 'ball' query to find all neighbors within a distance of 'r_max'. If you provide both, then it tries to find the specified 'num_neighbors' number of neighbors, but it will stop searching once the distance exceeds `r_max`. This method lets you specify a desired number of numbers while also preventing finding neighbors that are beyond some sensible cutoff, such as being across some interfacial boundary.

I'm making this an issue to remind myself it make the PR for this improvement :)

**Comment by vyasr** [comment]
Thanks Mike!
