### ISSUE TITLE
Add thresholds to filter results from Voronoi analysis

### ISSUE THREAD

**Issue by klywang** [glotzerlab/freud#584]
**Is your feature request related to a problem? Please describe.**
Voronoi polyhedra are very sensitive to small changes in particle position.  

**Describe the solution you'd like**
Add thresholds for Voronoi face areas/lengths. These may be defined as absolute thresholds or relative ones. 
Ideas for naming include @bdice suggestions of something like `ridge_threshold` for length/area thresholds or creating seperate parameters for relative or absolute thresholds for area and length, as in [OVITO](https://www.ovito.org/docs/current/particles.modifiers.voronoi_analysis.php).

**Additional context**
[Paper](https://www.pnas.org/content/112/43/E5769.short) that discusses topological instability of Voronoi cells.

**Comment by bdice** [comment]
@klywang I think this can be solved by fetching [the Voronoi NeighborList](https://freud.readthedocs.io/en/stable/modules/locality.html#freud.locality.Voronoi.nlist) and then using [its filter method](https://freud.readthedocs.io/en/stable/modules/locality.html#freud.locality.NeighborList.filter). There is an example here:

https://github.com/glotzerlab/freud/blob/16b9e232ba09d1cd2c689a249b2d9ea660764d73/tests/test_locality_Voronoi.py#L196-L201

@klywang Is that a good solution? Can this issue be closed?

**Comment by klywang** [comment]
@bdice Yeah that looks like a good solution!
