### ISSUE TITLE
Adding short examples to the following API: Cluster, Density, Environment, Locality, Order

### ISSUE THREAD

**Issue by mstryk** [glotzerlab/freud#623]
**Is your feature request related to a problem? Please describe.**
API could use more short examples in the documentation. The examples page of Freud includes too much depth for simple referencing purposes when using Freud.

**Describe the solution you'd like**
Commonly used modules should include 3-4 short examples. These examples should be less than 6 lines and be similar to those already in the box module.

**Additional context**
Trying to make Freud more user friendly for beginners.

**Comment by klywang** [comment]
I think this would be very helpful!
