### ISSUE TITLE
Memory leak in neighborlists from preprocess_arguments

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/freud#626]
**Describe the bug**
As reported in [this mailing list post](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/freud-users/q0LP_J_veLI), there appears to be a memory leak when `compute` is called for `SolidLiquid` without an explicit neighbor list, but instead with a set of query arguments. This issue is most likely arising due to some undesirable references floating around after creation in `_PairCompute._preprocess_arguments`, and merits further investigation.

**To Reproduce**
As in the mentioned post:

```
solidCalc = freud.order.SolidLiquid(normalize_q=True, l=6, q_threshold=0.7, solid_threshold=7)
nbDict = dict(mode='ball',r_max=1.4)
def orderParameter(snapshot):
    solidCalc.compute(snapshot, neighbors=nbDict)
    return solidCalc.largest_cluster_size
```

**Error output**
Memory usage grows each time the function is called.

**Comment by tommy-waltmann** [comment]
I've taken a look at this, and the issue appears to be that when you create the `nlist` from from the given argument dictionary, the python `NeighborList` object that is created will have a NULL reference to what is supposed to be its underlying cpp neighborlist, and therefore the python garbage collector will not manage the neighborlist reference that is later created in cpp.

This also explains why the other example he mention in his post, where he explicitly created a python neighborlist object and passed that to the SolidLiquid compute method, works just fine.

**Comment by tommy-waltmann** [comment]
This logical structure appears a lot in various calculations, pretty much anywhere we call `_preprocess_arguments()`. We could have these calculations hold a python neighborlist, and then set the python neighborlist to refer to the cpp neighborlist after `compute()` is called.

**Comment by vyasr** [comment]
@tommy-waltmann you're on the right track. The issue is definitely in that case, but I don't think it's because of the Python side. This code path is designed to allocate objects solely on the stack so that we don't have to think about this and so that we never depend on Python. The `NeighborList` that gets built internally should be immediately discarded. The problem is that there is break in this chain: one object is being allocated on the heap and not being immediately discarded. What we need to do is delete the `nlist` object created in `makeDefaultNList` (see `NeighborComputeFunctional.cc`) and this problem should go away. This issue is arising because we can't use smart pointers for the `toNeighborList` function of  (it's designed around the Cython API of freud) because we normally let Python manage the lifetime of these objects, but we're abusing it to for the use case where we need to build a `NeighborList` on demand. We're currently making an explicit copy of the heap-allocated `NeighborList` in that function and then returning that copy, so we simply need to free that memory and this problem should go away.

**Comment by klywang** [comment]
Would it be helpful to integrate tools that are designed to detect memory mismanagement to detect memory leaks in the future? I'm not sure what tool best suits our need, but there are many choices.

**Comment by tommy-waltmann** [comment]
I think this is in general a good idea, but I'm not aware of any tools that are designed for projects like ours. There are tools that work for pure c/cpp projects, but I'm not aware of any that will interface well with Cython.

**Comment by klywang** [comment]
It looks like [`Valgrind`](https://www.valgrind.org/) can be used with python to detect memory leaks in C++ [[x](https://pythonextensionpatterns.readthedocs.io/en/latest/debugging/valgrind.html#building-python-for-valgrind-label)] and [cython](https://github.com/cython/cython/wiki/UsingValgrindToDebug), although it's Linux only. I'm not sure how easy it would be to set up/use, but maybe this tool would be worth investigation.

Also sorry if this is too off topic/tangental for the issue. I can move this elsewhere if it is worth pursuing.

**Comment by bdice** [comment]
@klywang I successfully ran valgrind with freud once when debugging another memory issue, but it was very hard to understand its output because the C++ code generated by Cython is quite gross and generated a lot of false positives (iirc). I agree with @tommy-waltmann that most tools like this work much better with pure C/C++ projects. Another tool to be aware of is the `-fsanitize=address` compiler flag and other similar "sanitizers."

**Comment by vyasr** [comment]
@bdice is right that valgrind will generate a lot of false positives. In fact, the Python interpreter itself will generate a lot of false positives within valgrind as well, so even debugging a tool like HOOMD or numpy is pretty gross using valgrind. Having said that, it is a super useful tool and I would encourage its use for case-by-case debugging if you need it.

However, it's not quite the right tool for the job. valgrind is a *dynamic* tool, i.e. it's goal is to allow runtime detection of errors, but @klywang what we really want is a *static* linter. Tools that I've used for this in general in the past are clang-tidy and cppcheck. Applying something like this to freud was something I explored as part of the 2.0 release but I never got very far since we were in the middle of switching CI images (this issue, along with version problems, is also why clang-format is no longer run as part of CI, and we should go back to that). Adding a tool like this to our CI pipeline would definitely be useful and has been (very low) on my to-do list for a while.

**Comment by joaander** [comment]
It is a burden to maintain as python versions change, but you can make a suppressions file that filters out the false positives that come from Python itself. I used to do this for debugging HOOMD with valgrind.
