### ISSUE TITLE
1-d structure factor calculation

### ISSUE THREAD

**Issue by ramanishsingh** [glotzerlab/freud#652]
**Is your feature request related to a problem? Please describe.**
Right now freud does not compute 1-d structure factor. It would be nice to have that feature. 
The equation of the 1-d structure factor is given here : http://isaacs.sourceforge.net/phys/scatt.html (equation 1).

**Describe the solution you'd like**
Desired solution: A function that takes an mdtraj trajectory and gives out the structure factor (s(q) and q).

**Describe alternatives you've considered**

**Additional context**
This repository (MIT License) : https://github.com/mattwthompson/scattering/pulls has some tools to calculate scattering properties of materials. If needed, hints can be taken from this repo.

**Comment by bdice** [comment]
This demonstrates another approach using OVITO: https://www.ovito.org/forum/topic/calculation-of-the-structure-factor/

1. Use "Compute Property" to create a property with value 1 for all particles
2. Use "Spatial Correlation Function" with an appropriate FFT spacing to compute S(q)

![image](https://user-images.githubusercontent.com/3943761/118030322-bf097b00-b32a-11eb-87fa-1790a7a322ae.png)
