### ISSUE TITLE
Gaussian convolution of the parameter

### ISSUE THREAD

**Issue by pbuslaev** [glotzerlab/freud#666]
Hi,

I think that might be useful to extend GuassianDensity class to allow the convolution of the parameter. FX, if some parameter p is assigned to every atom in the box, its density function could be written as convolution of parameter for atom *l* with Dirac's delta function:

<img width="277" alt="image" src="https://user-images.githubusercontent.com/10205508/95256486-8f8e0f80-082b-11eb-8a38-f5951f468553.png">

For some tasks (e.g. studying phase transitions) the blurring of the parameter density function might be needed ([see for example](https://elifesciences.org/articles/13150)). Adding such option to GuassianDensity class is straightforward and would have solved the issue. The parameter list might be passed as an argument to *compute* method and C++ code at the very last step, the gaussian distribution should be multiplied by the parameter for the current point.

**Comment by bdice** [comment]
Hi @pbuslaev, thanks for the feature request!

If I understand correctly, you would like to provide an array `p` of length `N` (the number of particles) to `GaussianDensity.compute(system, p)` and weigh the contributions to the Gaussian Density by `p[i] * exp(...)`.

This appears to be the procedure in the paper section [Materials and Methods: Instantaneous Interface](https://elifesciences.org/articles/13150#s2) where the array `p` would be the order of each particle, <em>ϕ(r)</em> evaluated at each particle location <em>r<sub>i</sub></em>.

> Instantaneous interface
For the purpose of obtaining a smooth and continuous interface, ϕ(r) is coarse grained by replacing Dirac’s delta function with a finite-width Gaussian, (1/2πξ<sup>2</sup>)exp(−|r|<sup>2</sup>/2ξ<sup>2</sup>). The replacement changes ϕ(r) to ϕ<sup>bar</sup>(r). The coarse-graining width, ξ, is chosen to be the average separation between tail-end particles i and j when ⟨(ϕ<sub><em>l</em></sub>-⟨ϕ<sub><em>l</em></sub>⟩)(ϕ<sub><em>j</em></sub>−⟨ϕ<sub><em>j</em></sub>⟩)⟩/⟨(ϕ<sub><em>l</em></sub>−⟨ϕ<sub><em>l</em></sub>⟩)2⟩ in the ordered phase is 1/10. This choice yields a value of ξ=1.5 nm.

I would be happy to review a pull request that enables this feature. It would be a straightforward extension of the existing `GaussianDensity` code to incorporate an array of `values` just like in the class `freud.density.CorrelationFunction` (for ease of implementation, the values should probably be restricted to real numbers, not complex like `CorrelationFunction` allows).

I recommend following the API of `CorrelationFunction`. The `GaussianDensity` constructor would be the same, and it would accept an additional parameter in the `compute` method like `GaussianDensity(...).compute(self, system, values=None)`. The parameter `values` should be optional, with a default value of `None`. If `values is None`, then the default behavior would be equivalent to using an array of 1s, `np.ones(N, dtype=np.float32)`.

If you or another contributor would like help implementing this, please reach out! We have instructions for [compiling freud from source](https://freud.readthedocs.io/en/stable/gettingstarted/installation.html#compile-from-source) and a [developer guide](https://freud.readthedocs.io/en/stable/reference/development.html) that is mostly up-to-date.

I believe the changes needed are:
- `freud/density.pyx`: Add the parameter `values=None` to compute method, matching conventions like `_convert_array` (see `CorrelationFunction` for an example).
- `freud/_density.pxd`: Add an argument for the array of values, mirroring the behavior of `values` in `CorrelationFunction`.
- `cpp/density/GaussianDensity.h`: Add argument matching the type of that added to `_density.pxd`.
- `cpp/density/GaussianDensity.cc`: Add the argument and use the input values in the contribution.

**Comment by pbuslaev** [comment]
Hi @bdice! I will work on the code and send you a pull request then. Thanks for your in-depth explanation of how the implementation should be done.

**Comment by bdice** [comment]
@pbuslaev Fantastic! Looking forward to it. I recommend forking this repository and creating a branch `feature/gaussiandensity-values` on your fork for this work. Thanks for your willingness to contribute. 😄
