### ISSUE TITLE
Possible Memory Leak in Solid Liquid Order Parameter

### ISSUE THREAD

**Issue by alacour** [glotzerlab/freud#675]
**Describe the bug**
Repeatedly using freud.order.SolidLiquid results in a growing memory footprint.

**To Reproduce**
1. Repeatedly use freud.order.SolidLiquid on a system.
2. Check memory usage; it increases the numbers of calls.

**Error output**
No output

**System configuration (please complete the following information):**
 - OS: vislab
 - Version of Python: 3.8.5
 - Version of freud: 2.1.0

**Additional context**
This does not happen when repeatedly using freud.order.Steinhardt, so it seems particular to freud.order.SolidLiquid. I have tried passing in a custom neighborlist, calling delete on the object, and reinitializing the object, but the bug persists.

**Comment by bdice** [comment]
This is likely due to how SolidLiquid creates internal instances of Steinhardt and Cluster. Fixing this issue probably requires checking the lifetime of those internal objects and making sure they're destroyed.

**Comment by vyasr** [comment]
@alacour have you tried running on freud master? There are a couple of memory related fixes (specifically #626) that have been made since 2.1.0 that might resolve your problem.

@bdice I'm pretty sure those are stored as member objects, not pointers of any sort, but certainly worth verifying.

Brief Update:
SolidLiquid uses makeDefaultNlist internally, which is what was fixed by #626 and I suspect that's the culprit.

**Comment by tcmoore3** [comment]
> @alacour have you tried running on freud master? There are a couple of memory related fixes (specifically #626) that have been made since 2.1.0 that might resolve your problem.
> 
> @bdice I'm pretty sure those are stored as member objects, not pointers of any sort, but certainly worth verifying.
> 
> Brief Update:
> SolidLiquid uses makeDefaultNlist internally, which is what was fixed by #626 and I suspect that's the culprit.

This fix should be listed in [the changelog](https://github.com/glotzerlab/freud/blob/master/ChangeLog.md).

**Comment by vyasr** [comment]
Agreed, somehow that slipped through the cracks.

**Comment by vyasr** [comment]
I've updated the changelog, but we need to confirm that that fix actually resolves this reported issue.

**Comment by vyasr** [comment]
@alacour I'm going to assume that you're not running into this issue anymore and that #626 was the necessary fix. Feel free to reopen otherwise.
