### ISSUE TITLE
Wrong constructor arguments in correlation function docs

### ISSUE THREAD

**Issue by tcmoore3** [glotzerlab/freud#721]
**Describe the bug**
The [docs for `freud.density.CorrleationFunction`](https://freud.readthedocs.io/en/stable/modules/density.html#freud.density.CorrelationFunction) mention an argument `dr` for the constructor, but the actual constructor arguments are `bins` and `r_max`. 

**To Reproduce**
1. Go to the [the docs](https://freud.readthedocs.io/en/stable/modules/density.html#freud.density.CorrelationFunction)
2. Read the information listed under `freud.density.CorrelationFunction`

**Additional context**
Will fix, making issue for reference.

**Comment by bdice** [comment]
Thanks @tcmoore3 for the bug report, and volunteering to fix it!
