### ISSUE TITLE
Document/fix units for k vectors in diffraction

### ISSUE THREAD

**Issue by tcmoore3** [glotzerlab/freud#723]
These units are not currently documented, but they should be. Note, the units are not too important for visualization, as a large fraction of users use the diffraction to detect the presence of order within systems. However, if you want to do quantitative analyses with the diffraction pattern, the magnitudes of the k-vectors is quite important.

**Comment by bdice** [comment]
Specifically we need to document whether factors of 2pi are included. I believe they are not, and that the k-vectors are simply in inverse length units as opposed to reciprocal vectors which are different by 2pi. The documentation should specify something like the behavior of `\exp^{i \vec{k} \cdot \vec{r}}` (2pi is accounted for in the k-vector) versus `\exp^{2 \pi i \vec{k} \cdot \vec{r}}` (2pi is not accounted for in the k-vector).

Though this is marked as a documentation issue, I think it is worth getting a few opinions and possibly changing the behavior, this is arguably a bug.

**Comment by bdice** [comment]
Here is a notebook documenting some intermediate work on this. The math in `DiffractionPattern` will need to be updated.
[spacing-output_size.zip](https://github.com/glotzerlab/freud/files/6542057/spacing-output_size.zip)
