### ISSUE TITLE
Freud API docs aren't loading on readthedocs.io

### ISSUE THREAD

**Issue by chrisjonesBSU** [glotzerlab/freud#735]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

The API specific documentation isn't loading for me on freud's readthedocs site. The pages load ok, but they are blank.

I've tried it with Firefox on Linux and Safari on MacOS with the same results.

**Comment by bdice** [comment]
@chrisjonesBSU We're aware of the problem -- there were some issues in the build system and how it detects conda. We attempted to fix them for v2.5.0 but apparently this broke ReadTheDocs. You can use the docs for v2.4.1.

**Comment by vyasr** [comment]
I've temporarily repointed our `stable` docs to the 2.4.1 docs until our next release.

**Comment by vyasr** [comment]
I lied, we can't do that anymore because the changes to the TBB API make it impossible to rebuild old versions of the docs again. I'll switch this back, we're stuck with broken builds until #736 is fixed.

**Comment by bdice** [comment]
@chrisjonesBSU The "latest" docs are working now. https://freud.readthedocs.io/en/latest/
