### ISSUE TITLE
Steinhardt OP Performance Improvements and Potential API Change

### ISSUE THREAD

**Issue by b-butler** [glotzerlab/freud#747]
## Description

Using multiple `Steinhardt` objects to compute different `l` values is significantly slower than using `LocalDescriptors` with a custom Numba function to compute Steinhardt OP from the spherical harmonics.

I profiled both code paths with pre-computed neighbor lists for computing all Minkowski structure metrics (i.e. weighted Steinhardt) up to `l=12` and found three reason for the difference in speed.
1. `PointSphEvaluator::compute` computes for all `l` values up to some maximum (in the `fsph` library).
2. The construction of `PointSphEvaluator` for each `Steinhardt` object is costly as the constructor is not a trivial one.
3. The repeated iteration over the neighbor list.

The difference in performance is mostly due to the first two reason.

## Potential Solutions

* Allow for `fsph` to only compute the desired spherical harmonics.
* Move the computational cost of constructing `PointSphEvaluator` objects outside the constructor (likely more involved than the point above).
* Allow `Steinhardt` to compute the Steinhardt OP for multiple `l` (negates the need for the above bullet). We can do this without changing API by
  + Returning the same shaped arrays when a single `l` is chosen
  + Allowing either a sequence of ints or an int in the constructor of `Steinhardt`
  + Returning a list of ints or an int conditionally for the `l` property based on the number of `l` chosen
 
With respect to `fsph` we could allow for two types of selections either ranges (e.g. [4, 6], [0, 4]) or arbitrary `l` (e.g. [1, 4, 3, 9]). The first is likely easier to implement, but this could also change how we would go about extending the `Steinhardt` class if we chose to do so.

## Alternatives

I can keep using my custom Numba solution for now.

@klarh @bdice let me know of any thoughts you have regarding this.

Edit:
I am linking the notebook I used for the original benchmarking, and the Python scripted used for profiling with
[freud-benchmark.zip](https://github.com/glotzerlab/freud/files/6288469/freud-benchmark.zip)
 `py-spy`.

**Comment by klarh** [comment]
I think that accepting a list of l's in the Steinhardt order parameter compute would make a lot of sense and be the most straightforward way to make this work efficiently.

**Comment by bdice** [comment]
Thanks @b-butler for looking into this and the great write-up of your results. It sounds like changes would be needed in both freud and fsph to solve this issue (perhaps mostly fsph?).

From the API side, my only possible hesitation would be that users are probably just as likely to want `[q4, q6, w4, w6]` or similar combinations, which this wouldn't allow. While the proposed API of a sequence of l-values is a strict improvement over the current limitation to one l-value, it does no better to address that common user need (mixing l values and other parameters). I strongly favor arbitrary l-values over the range syntax. That is, `[0, 4]` should be l=0 and l=4, not l=0,1,2,3,4 or l=0,1,2,3.

edit: I'm not sure what I would propose as an API for the use case I mentioned of `[q4, q6, w4, w6]`. Just wanted to mention that in case it sparks ideas for a better overall API in freud 3.0.

**Comment by bdice** [comment]
> 
> 
> I think that accepting a list of l's in the Steinhardt order parameter compute would make a lot of sense and be the most straightforward way to make this work efficiently.

@b-butler Would this be a complete-enough solution? Or would fsph changes also be necessary? I wasn't sure about that from the original comment.

**Comment by b-butler** [comment]
@bdice my understanding is that this would also need changes to `fsph` to be as efficient as possible, but it shouldn't be any worse than `LocalDescriptors` with a custom Numba function.

**Comment by b-butler** [comment]
@bdice should we have a list/vector of `q` arrays to avoid unused array entries for arrays that depend on the `m` values or just leave those unpopulated with zero? My instinct is yes, because otherwise we will waste a lot of space and likely confuse users.

**Comment by klarh** [comment]
I'm not sure exactly what changes are being proposed here for `fsph`, but I wouldn't expect it to save a lot of time to skip calculating particular spherical harmonics (at least compared to the development effort involved in getting the data dependencies and indexing correct). Once the whole set of spherical harmonics is calculated for a given coordinate, though, it would be very straightforward for `Steinhardt` to calculate all of the `q`'s and `w`'s for whichever set of spherical harmonic degrees it would like.

**Comment by bdice** [comment]
@b-butler I don't think I understand what you mean by unused array entries, but it sounds like you have a design in mind that will be efficient and relatively easy to understand. I would say "just go for it" and start a pull request. Then we can iterate on the design with a more concrete discussion.

**Comment by b-butler** [comment]
@klarh that is what I was thinking. We would calculate the spherical harmonics up to the highest we need, and only further process the ones we want.

I was referring to if we store the `qmli` and like in one large array or use a vector of them to avoid dealing with the fact that the `m` dimension depends on `l`. I will open a PR with my design soon hopefully and we can iterate on that.
