### ISSUE TITLE
Wrong return value in docs for NeighborQuery.plot()

### ISSUE THREAD

**Issue by tcmoore3** [glotzerlab/freud#763]
**Describe the bug**
The [docs for `NeighborQuery.plot()`](https://freud.readthedocs.io/en/stable/modules/locality.html#freud.locality.NeighborQuery.plot) show that just the `matplotlib.axes.Axes` is returned, but the entire `PathCollection` (i.e., the set of points in the scatter plot) is also returned.

**Comment by bdice** [comment]
I think that's intentional behavior, I probably added this so that the colors / etc. could be edited. Good catch, a doc fix would be welcome.
