### ISSUE TITLE
Steinhardt average value are incorrectly computed.

### ISSUE THREAD

**Issue by bdice** [glotzerlab/freud#795]
Analysis by @arvdee identified that freud's Steinhardt order parameters are not being computed correctly for `average=True`.

This issue is primarily meant to document the existence of the problem. This thread on the user forum includes extensive details: https://groups.google.com/g/freud-users/c/zpR9UEkDhow/m/KGoixKrrBAAJ

I have created a fix and plan to apply it once #794 and #773 are merged.

The cause is that the `computeAve` function is looping over two neighbor shells instead of one.

I have a repository here that I plan to adapt for freud's validation tests: https://github.com/bdice/freud_boops_accuracy

@arvdee Can you and your colleague who provided the "GC" data provide us with permission to include the `Test_Configuration` files and the corresponding Steinhardt/MSM reference data in freud's source code for use as validation tests?

This bug affects all versions of freud 2.x up to now.

**Comment by vyasr** [comment]
Thanks for your super detailed analysis on this @ArvDee!

**Comment by ArvDee** [comment]
My pleasure @vyasr. It's a sneaky bug, so it kind of had to be quite detailed! And @bdice yes, sure, both GC and I are fine with you including the data as tests. Thanks for the quick responses and (soon) fix.
