### ISSUE TITLE
Introduce `@pytest.mark.parametrize` to unit tests

### ISSUE THREAD

**Issue by andkerr** [glotzerlab/freud#814]
Many of Freud's unit tests currently implement `for` loops to test various combinations of input parameters. For example, test_diffraction_DiffractionPattern.py currently includes:
```
for grid_size in (256, 1024):
    for output_size in (255, 256, 1023, 1024):
          for zoom in (1, 2.5, 4.123):
```
in the test for diffraction peaks in a simple cubic system.

With `@pytest.mark.parametrize`, the code above can refactor to
```
@pytest.mark.parametrize("grid_size, output_size, zoom", [
    (grid_size, output_size, zoom)
    for grid_size in (256, 1024)
    for output_size in (255, 256, 1023, 1024)
    for zoom in (1, 2.5, 4.123)
])
```
and be placed immediately before the simple cubic system test function. When run with pytest,
the printout will show a test for each combination of parameters, and whether is passes or not. This modification may also make tests easier to read.

This issue proposes similar changes to all of Freud's unit tests, replacing nested `for` loops with the appropriate `@pytest.mark.parameterize`expression.

Care must be taken to avoid changing tests such that they always pass.

**Comment by vyasr** [comment]
For whoever tackles this issue it may also be worth assessing if we really need to test as many different parameter sizes as we do now. I did some work a while back to reduce the time it takes to run freud tests, but we could probably cut it even a little bit further since in many cases I don't think our different case are really adding meaningful additional validation.

**Comment by ThenoobMario** [comment]
Hello,

I just discovered this project and after skimming through the docs and the code, I would like to work on this issue. I may not be the best person for this, but I would surely like to try!

**Comment by vyasr** [comment]
@ThenoobMario I sincerely apologize for not noticing your message earlier. I had to take a step back from this repository for a while and completely missed your request. If you are still interested feel free to take a stab at this!

**Comment by ThenoobMario** [comment]
Hello @vyasr, thank you for responding. Yes, I am excited to take this up and will start working on it!

**Comment by vyasr** [comment]
@ThenoobMario sounds great. Is the description clear enough for you to understand how to proceed? Let us know if you need additional guidance.

**Comment by ThenoobMario** [comment]
@vyasr Yes, the description seems clear enough for now. I will take some time to familiarise myself with the software first and then start working on this issue. Will reach out to you here for help :)
