### ISSUE TITLE
Require r_min >= 0 at the C++ level.

### ISSUE THREAD

**Issue by bdice** [glotzerlab/freud#821]
Currently the C++ code in freud does not ensure that `r_min` is non-negative (>= 0) in several classes. Values of `r_min < 0` should raise an error in the constructor like this:

https://github.com/glotzerlab/freud/blob/eb2a97bac302ed45236f26e0a7e6a0346071c579/cpp/density/RDF.cc#L17-L28

This applies to classes like `RDF` ~and `CorrelationFunction`~ and other classes that deal with radial distances that cannot be negative. This also affects `NeighborQuery` related classes, like `NeighborQueryPerPointIterator` (and related query constructors) and the method `NeighborList.filter_r`.

The structure factor calculations in #660 and #820 have `k_min` values where this same rule should apply (but that can be resolved in those PRs before merging them).

Fixing this will require tests that check for invalid values and ensure that an error is raised.

## Unwanted behavior:
```python
>>> freud.density.RDF(100, 10, r_min=-1)
freud.density.RDF(bins=100, r_max=10.0, r_min=-1.0
```

## Desired behavior:
```python
>>> freud.density.RDF(100, 10, r_min=-1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "density.pyx", line 615, in freud.density.RDF.__cinit__
ValueError: RDF requires r_min to be non-negative.
```

**Comment by SYEDZIAULISLAM** [comment]
@bdice what was the exact issue over here? as i seen that **r_min** are not defined in the class like **"CorrelationFunction"** and many class does not have **r-min** value.

**Comment by bdice** [comment]
@SYEDZIAULISLAM Good catch, the `CorrelationFunction` class doesn't support `r_min`. It's just defined with `r_min=0`.
https://github.com/glotzerlab/freud/blob/eb2a97bac302ed45236f26e0a7e6a0346071c579/cpp/density/CorrelationFunction.cc#L36

This issue definitely applies to `RDF` and the `NeighborQuery` classes mentioned above, which do take `r_min` parameters. There may not be any other classes that this affects. Part of resolving this issue will be to verify that there are no other exceptions.

**Comment by SyedZiaul** [comment]
@bdice could you check whether #825 solve this issue .

**Comment by vyasr** [comment]
#825 is only a partial resolution of this issue, see [#825 (comment)](https://github.com/glotzerlab/freud/pull/825#issuecomment-913825792).

**Comment by AlainKadar** [comment]
@tommy-waltmann can this be closed? I've just been browsing Issues and it seems this one is all fixed.

**Comment by tommy-waltmann** [comment]
Good catch @AlainKadar , this does appear to be resolved.
