### ISSUE TITLE
util::Histogram<T>::Axes should be exposed as util::Axes

### ISSUE THREAD

**Issue by bdice** [glotzerlab/freud#826]
**Is your feature request related to a problem? Please describe.**
The code I'm writing for #820 and the code for `CorrelationFunction` both require two histograms: one for computing the values S(k) or C(r) and a second histogram used for normalizing the bin counts. In both cases, the same `Axes` object could be used twice.

However, the `Axes` object (which does not depend on the `util::Histogram<T>` or type `T`) is currently exposed only in the `util::Histogram<T>` namespace as `util::Histogram<T>::Axes`. It seems that this should be exposed as `util::Axes`. I accidentally re-used the `axes` instance with a different `T` and it worked fine, as expected.

**Describe the solution you'd like**
Move `using Axes = std::vector<std::shared_pointer<Axis>>` outside of the `Histogram` class, to just below the `Axis` class.

I think `AxisIterator` can be removed -- it is not used in the code.

Then the `CorrelationFunction` can be refactored to use only one `Axes` instance for both histograms. (It is already possible to use the same `Axes` instance for both histograms, but this is not obvious because the type name includes the `Histogram<T>` namespace.)

**Comment by vyasr** [comment]
These changes should be fine. The `AxisIterator` is a trivial alias anyway and calling `Axes::iterator` or `Axes::const_iterator` is probably preferable.
