### ISSUE TITLE
Build Failures with TBB on Ubuntu 20.04

### ISSUE THREAD

**Issue by tommy-waltmann** [glotzerlab/freud#866]
**Describe the bug**
Builds fail, saying they cannot find TBB's include directories.

**To Reproduce**
Install tbb using the apt package manager with the system configuration defined below, and then build freud with
```
python setup.py install --user
```

**Error output**
CMake cannot find TBB's include directories. The CMake output complains about the variable `TBB_INCLUDE_DIR` being set to `NOTFOUND`.

**System configuration (please complete the following information):**
 - OS: Ubuntu 20.0.4 on WSL
 - Version of Python: 3.8
 - Version of freud: 2.7.0

**Additional context**
I found this error while trying to help a new student @marxd1 build freud with the above system configuration. The good news is that we have already pinpointed the problem: line 64 of the top-level `CMakeLists.txt` should read
```
if(NOT TBB_INCLUDE_DIR OR NOT TBB_LIBRARY)
```
instead of
```
if(NOT DEFINED TBB_INCLUDE_DIR OR NOT DEFINED TBB_LIBRARY)
```

Freud's FindTBB.cmake necessarily defines the variables `TBB_INCLUDE_DIR` and `TBB_LIBRARY`, but if it doesn't actually find them on the system, it sets their value to `NOTFOUND`. In this case, the check with `DEFINED` evaluates to true instead of what it should evaluate to, false. 

After some more discussion with @joaander, he noted that freud doesn't use the modern CMake approach of just linking the build target `TBB::tbb` to `libfreud` via `target_link_libraries` after a call to `find_package`. This is another thing worth fixing in a PR to fix the above build issue.

**Comment by bdice** [comment]
@tommy-waltmann Can you add the versions of the apt packages you have installed on this issue? Both the library [libtbb2](https://packages.ubuntu.com/focal/libtbb2) and its headers [libtbb-dev](https://packages.ubuntu.com/focal/libtbb-dev). I wonder if this is something changed with newer TBB packages (>2020), since I am pretty confident this worked at one point.

**Comment by tommy-waltmann** [comment]
both are the default for 20.04 apt downloads: 2020.1-2. FWIW, everything works on my machine which has the same system configuration except for Ubuntu 18.04 and the 2017~U7-8 release.

**Comment by joaander** [comment]
Specifically, I recommend removing:
https://github.com/glotzerlab/freud/blob/8968f8cda07ecf4ed3ef1c64d77a99e5381404c6/CMakeLists.txt#L106
and
https://github.com/glotzerlab/freud/blob/8968f8cda07ecf4ed3ef1c64d77a99e5381404c6/cpp/CMakeLists.txt#L35

In this way, there is no need to manage `TBB_*_` variables separate from the `TBB::tbb` target.
