### ISSUE TITLE
Cannot import StaticStructureFactorDirect

### ISSUE THREAD

**Issue by donshen** [glotzerlab/freud#868]
**Describe the bug**
Cannot import the StaticStructureFactorDirect module from freud.diffraction

**To Reproduce**
from freud.diffraction import StaticStructureFactorDirect

**Error output**
ImportError                     Traceback (most recent call last)
<ipython-input-2-68341542d56c> in <module>
----> 1 from freud.diffraction import StaticStructureFactorDirect

ImportError: cannot import name 'StaticStructureFactorDirect' from 'freud.diffraction' (/path/to/freud/diffraction.cpython-37m-x86_64-linux-gnu.so)

**System configuration (please complete the following information):**
 - OS: [e.g. macOS]
 - Version of Python [e.g. 3.7]
 - Version of freud [e.g. 2.7.0]

**Additional context**

**Comment by donshen** [comment]
Tried pip install, conda install, and compile from source, in all the cases the StaticStructureFactorDirect cannot be imported but StaticStructureFactorDebye works.

**Comment by bdice** [comment]
@donshen This feature was merged recently and has not yet been released to PyPI or conda-forge. Our documentation is built from the latest commit on the `master` branch so you should be able to get this feature if you compile from source.

**Comment by donshen** [comment]
> @donshen This feature was merged recently and has not yet been released to PyPI or conda-forge. Our documentation is built from the latest commit on the `master` branch so you should be able to get this feature if you compile from source.

Thanks, tried compiling again this works. Thanks for the new feature!
