### ISSUE TITLE
flake8 4 does not support Cython

### ISSUE THREAD

**Issue by bdice** [glotzerlab/freud#884]
https://github.com/glotzerlab/freud/blob/b960cab58da599a4437dbd9f7920098b1b6941bc/.pre-commit-config.yaml#L46

flake8 4 does not support Cython, according to the issue linked below. We will need to figure out how to pin this pre-commit hook and disable automatic updates so that it does not get updated to 4.0.

This is quite unfortunate, as many packages rely on flake8 for Cython linting and many blog posts / StackOverflow questions have been dedicated to the topic of ignoring Cython syntax differences so that the majority of linter checks still work with Cython.

https://github.com/PyCQA/flake8/issues/1482

**Comment by matthewfeickert** [comment]
> We will need to figure out how to pin this pre-commit hook and disable automatic updates so that it does not get updated to 4.0.

:wave: You won't be able to, for better or for worse. If you use `pre-commit.ci` then you need to choose some autoupdate schedule (as you have)

https://github.com/glotzerlab/freud/blob/b960cab58da599a4437dbd9f7920098b1b6941bc/.pre-commit-config.yaml#L1-L2

and an option to disable updates has been rejected in the past in https://github.com/pre-commit-ci/issues/issues/83.

**Comment by bdice** [comment]
flake8 was updated to 4.0.1 in #896. @tommy-waltmann tagging you for awareness here. It looks like tests passed because we ignore E999 (`SyntaxError: invalid syntax`). However, we probably want to drop flake8 checks for Cython files and stop ignoring E999. I'll make a follow-up PR to do that.

**Comment by bdice** [comment]
Related: https://github.com/kmaehashi/flake8-force
