### ISSUE TITLE
Does manual not update in finding neighbors?

### ISSUE THREAD

**Issue by Roy-Kid** [glotzerlab/freud#885]
**Describe the bug**
I can run the example in [finding neighbors](https://freud.readthedocs.io/en/latest/gettingstarted/tutorial/neighborfinding.html). It tells me that 
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/work/molpy/molpy/box.py in <module>
      9 points = np.random.rand(num_points)*L - L/2
     10 box = freud.box.Box.cube(L)
---> 11 aq = freud.locality.AABBQuery(box, points)
     12 
     13 # Now we generate a smaller sample of points for which we want to find

locality.pyx in freud.locality.AABBQuery.__cinit__()

util.pyx in freud.util._convert_array()

ValueError: array.ndim = 1; expected ndim = 2
```

**To Reproduce**
Just run this code

```
import numpy as np
import freud

# As an example, we randomly generate 100 points in a 10x10x10 cubic box.
L = 10
num_points = 100

# We shift all points into the expected range for freud.
points = np.random.rand(num_points)*L - L/2
box = freud.box.Box.cube(L)
aq = freud.locality.AABBQuery(box, points)

# Now we generate a smaller sample of points for which we want to find
# neighbors based on the original set.
query_points = np.random.rand(num_points/10)*L - L/2
distances = []

# Here, we ask for the 4 nearest neighbors of each point in query_points.
for bond in aq.query(query_points, dict(num_neighbors=4)):
    # The returned bonds are tuples of the form
    # (query_point_index, point_index, distance). For instance, a bond
    # (1, 3, 0.2) would indicate that points[3] was one of the 4 nearest
    # neighbors for query_points[1], and that they are separated by a
    # distance of 0.2
    # (i.e. np.linalg.norm(query_points[1] - points[3]) == 2).
    distances.append(bond[2])

avg_distance = np.mean(distances)
```

**Error output**
If applicable, add terminal output or screenshots to help explain your problem.

**System configuration (please complete the following information):**
 - OS: Ubuntu20
 - Version of Python 3.9
 - Version of freud latest

**Comment by bdice** [comment]
I think this is a typo in the example. The random point generation should say:

```python
np.random.rand(num_points, 3)
```

to generate an array with x, y, and z components. @Roy-Kid Would you be willing to open a PR for this fix? This is the file to edit: https://github.com/glotzerlab/freud/blob/master/doc/source/gettingstarted/tutorial/neighborfinding.rst

**Comment by Roy-Kid** [comment]
Yes, I have fixed it and start a pr #886. I like your neighborlist design. BTW, do you have some modules to set up cell list ?

**Comment by bdice** [comment]
> BTW, do you have some modules to set up cell list ?

I'm not sure exactly what you mean by this. The freud package has a [LinkCell](https://freud.readthedocs.io/en/latest/modules/locality.html#freud.locality.LinkCell) class in Python that can be used to find neighbors with a linked cell list data structure. This code is based on the implementation of linked cell lists in HOOMD-blue. The algorithm is implemented in C++ and its source code is in this directory: https://github.com/glotzerlab/freud/tree/master/cpp/locality

**Comment by Roy-Kid** [comment]
Thanks a lot! That is what I need. I am writing a [package](https://github.com/Roy-Kid/molpy) that needs an efficient cell & neighbor list. I really like your design and code style, so I consider if I import your brilliant work as the core of my work. I will read your code carefully. Thank again.

**Comment by Roy-Kid** [comment]
wow, your group developed hoomd-blue! I learned a lot from this MD software and its docs. It made me very interested in MD!

**Comment by bdice** [comment]
Awesome. As a note, we usually see better performance from the [AABBQuery](https://freud.readthedocs.io/en/latest/modules/locality.html#freud.locality.AABBQuery) class, which uses an axis-aligned bounding box, compared to the LinkCell class.

You may also like to see the MoSDeF tools `mbuild`, `gmso`, and `foyer` if you work with chemical topologies and force fields. https://mosdef.org/ These are built by some of our collaborators.

**Comment by bdice** [comment]
Also you may like to see the benchmarks here. They are a little out of date but should still be generally accurate:
- Rendered in the docs: https://freud.readthedocs.io/en/latest/gettingstarted/examples/examples/Benchmarking%20Neighbor%20Finding%20against%20scipy.html
- Source notebook: https://github.com/glotzerlab/freud-examples/blob/master/examples/Benchmarking%20Neighbor%20Finding%20against%20scipy.ipynb

**Comment by Roy-Kid** [comment]
I appreciate your information! It helps me a lot!

> Awesome. As a note, we usually see better performance from the [AABBQuery](https://freud.readthedocs.io/en/latest/modules/locality.html#freud.locality.AABBQuery) class, which uses an axis-aligned bounding box, compared to the LinkCell class.
> 
> You may also like to see the MoSDeF tools `mbuild`, `gmso`, and `foyer` if you work with chemical topologies and force fields. https://mosdef.org/ These are built by some of our collaborators.

MOSDEF did all I wanted to do, and I suddenly began to be confused about what to do next.

**Comment by Roy-Kid** [comment]
And I have a question: how faster use cython /C++ to do math operations in freud than using pure python/numpy? I have no concept of it and need to decide what I should use. If you can help me with it that would save a lot of time!

**Comment by bdice** [comment]
Linear algebra and matrix operations in NumPy use fast math libraries in C. However, finding particle neighbors efficiently is not just a linear algebra problem. The data structures like AABBQuery and LinkCell are implemented in C++ and use a library called oneTBB for parallelism (some of which uses concurrency in LinkCell for efficient lookup of the neighbor cells). I would recommend reading our publication about freud's design here for more information. https://freud.readthedocs.io/en/latest/reference/citing.html

Overall, NumPy is an excellent choice for pure vector/matrix math, but more complicated data structures may benefit from code in a lower level language like C++, especially if parallelism can be used to accelerate computations. We choose Cython for familiarity. Pybind11 is another good option for adding Python bindings to C++ code.

**Comment by Roy-Kid** [comment]
I do thank you for your kindly help! I learned a lot from your answer and the code! I need to read the code about linkedcell and AABB neighborlist!
