### ISSUE TITLE
I can't find the trajectory function from freud.

### ISSUE THREAD

**Issue by zhangyemayapro** [glotzerlab/freud#887]
My teacher gave me a code where trajectory function is used:

`from freud import trajectory`

but I can't find it in all freud versions.
thanks for your help~

**Comment by vyasr** [comment]
`freud.trajectory` was removed in v0.6.0 in 2016. You can try to build freud v0.5.4, but unfortunately the package has been essentially completely rewritten multiple times in the past 5 years so your mileage may vary and most of the current package maintainers won't have much familiarity with the code as of then. If you know what you're trying to achieve, you will likely have better luck trying to rewrite your code to use a modern version of freud >=2.0.

I'm going to close this issue as resolved for now, but feel free to reopen and comment if this doesn't address your question sufficiently.
