### ISSUE TITLE
i can't install freud 0.6.4?

### ISSUE THREAD

**Issue by zhangyemayapro** [glotzerlab/freud#889]
I follow the step in doc 0.6.4 to install freud
'
$: conda config --add channels glotzer
$: conda config --add channels file:///nfs/glotzer/software/conda-private
$: conda install freud
'
I got an error：
Collecting package metadata (current_repodata.json): failed

UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: conda-private
  channel url: file:///nfs/glotzer/software/conda-private
  error code: 404

Thanks for your help~

**Comment by bdice** [comment]
The instructions you wrote above were designed for use with local NFS systems (not accessible to the public) that no longer exist. Please upgrade to a currently supported version of freud >=2.0 if you would like to receive support from the community. The `glotzer` conda channel has not been used in several years, we have transitioned to using conda-forge for distribution.

The current installation instructions are located here: https://freud.readthedocs.io/en/latest/gettingstarted/installation.html

**Comment by zhangyemayapro** [comment]
thanks for your help~
