### ISSUE TITLE
Units for the voronoi volumes? 

### ISSUE THREAD

**Issue by vk208** [glotzerlab/freud#944]
Hi, I've successfully used the voro.compute(box, positions).volumes function and I got a histogram but I'm trying to determine the units for the VC areas. Is it in the documentation somewhere? I couldn't seem to find it.

**Comment by b-butler** [comment]
This is based on the units of your system (e.g. the units of the box).

**Comment by tommy-waltmann** [comment]
Hi,

Remember that the voronoi volumes are just that, volumes. The units are the length units of the points given to it raised to the third power, or squared in 2d.

Hope this clears it up. If you have any more questions please ask.

**Comment by vk208** [comment]
Thanks for the clarification and the quick response: I appreciate it!
