### ISSUE TITLE
Cite Erin Teich's "identity crisis" paper for environment matching

### ISSUE THREAD

**Issue by tcmoore3** [glotzerlab/freud#977]
I believe `EnvironmentMotifMatch`, the ~artist~ algorithm formerly known as `MatchEnv`, was first developed and implemented for [Erin's 2019 "identity crisis"](https://www.nature.com/articles/s41467-018-07977-2) paper. If that's the case, we should add a note in the docs that users should cite that paper if they use that method. If that's not the case, there is probably something else we should advise users to cite.

I could certainly be wrong about this, so maybe those who know the history of the code better than me (@vyasr , @bdice , @joaander , @harperic ) can offer some input.

**Comment by vyasr** [comment]
That is correct. The supplement of that paper contains the original description of the method.
