### ISSUE TITLE
Remove zero vectors from the clusters computed by EnvironmentCluster

### ISSUE THREAD

**Issue by Charlottez112** [glotzerlab/freud#981]
Right now the clusters found by `EnvironmentCluster` are padded with 0 vectors if their sizes (number of component particles) are smaller than the largest cluster. This can be confusing, and it's not necessary.  Based on recent discussions in #979, it seems like a better approach would be returning a list of numpy arrays, rather than a 2D numpy array with zeros.

`point_environments` computed by `EnvironmentCluster` are also padded with zeros. We will need to remove zero vectors from those too. (discussed in #980)

**Comment by tommy-waltmann** [comment]
Closed via #1064
