### ISSUE TITLE
2D Debye Structure Factor incorrectly uses 3D formula

### ISSUE THREAD

**Issue by bdice** [glotzerlab/freud#985]
@DomFijan @tommy-waltmann I'm not sure if PR #936 is correctly analyzing the physics of the 2D problem. I threw an error for 2D calculations for a reason, and should have left a comment about why. It requires a derivation which I have finally done and shown below, with a reference.

Copying a derivation of the Debye formula from https://github.com/wojdyr/debyer/blob/master/doc/index.rst and adapting it for 2D:

> Let's re-derive it once more. We start with the amplitude of the scattered wave. If we ignore non-elastic scattering and assume that each photon is scattered only once, the amplitude is a simple sum over all atoms:
> $$\Psi(\boldsymbol{Q}) = \sum_i \psi_i =\sum_i f_i \exp(-i \boldsymbol{Q} \cdot \boldsymbol{r}_i)$$
> (*i* has two unrelated meanings here, index and the imaginary unit, hopefully it's not too confusing).
> The intensity of the scattered wave is given as
>
> $$I(\boldsymbol{Q}) = \left| \Psi (\boldsymbol{Q}) \right|^2 = \Psi(\boldsymbol{Q}) \Psi^{*}(\boldsymbol{Q})$$
>
> where the complex conjugate
>
> $$\Psi^{*}(\boldsymbol{Q}) = \sum_i \psi^{*}_i = \sum_i f_i^{*} \exp(i \boldsymbol{Q} \cdot \boldsymbol{r}_i)$$
>
> Therefore, with the assumption that atomic form factors are real and $f^{*}=f$,
>
> $$I(\boldsymbol{Q}) = \sum_i \sum_j \psi_i \psi^{*}_j = \sum_i \sum_j f_i f_j \exp \left[ -i \boldsymbol{Q} \cdot \left(\boldsymbol{r}_i-\boldsymbol{r}_j \right) \right]$$
>
> The Debye scattering equation gives spherically averaged intensity. The averaging is similar to calculating the surface area of sphere. It is more elegant to use double integral, but knowing the circumference formula we can take a shortcut and use one integral:
> $$A_{sphere} = \int_0^\pi 2\pi r\sin\theta \, r \mathrm{d} \theta = 2\pi r^2 [ - \cos \theta ]_0^\pi = 4 \pi r^2$$
>
> Now, let $\gamma$ be the angle between $Q$ and $r_{ij}$.
>
> $$I(\boldsymbol{Q}) = \sum_i \sum_j f_i f_j \exp \left( -i Q r_{ij} \cos \gamma \right)$$
>
> Averaging the exponential part gives
>
> $$\left\langle \exp( -iQr_{ij} \cos \gamma ) \right\rangle = \frac{1}{4\pi r_{ij}^2} \int_0^\pi \exp\left( -iQr_{ij} \cos\gamma
    \right) ~2\pi r_{ij}^2 \sin\gamma ~\mathrm{d}\gamma$$
>
> $$= \frac{1}{2} \int_0^\pi \exp\left( -iQr_{ij} \cos\gamma \right) \sin\gamma ~\mathrm{d}\gamma$$
>
> $$= \frac{1}{2} \left[ \frac{\exp\left( -iQr_{ij} \cos\gamma \right)} {iQr_{ij}} \right]_0^\pi$$
>
> $$= \frac{\exp(iQr_{ij})-\exp(-iQr_{ij})}{2iQr_{ij}}$$
>
> $$= \frac{\sin(Qr_{ij})}{Qr_{ij}}$$
>
> which proves the Debye formula.

Because 2D uses polar coordinates and not spherical coordinates, the $\sin\gamma$ term goes away. This fundamentally changes the integral.

For 2D,

$$A_{circle} = \int_0^{2 \pi} r~\mathrm{d} \theta = 2\pi r$$

Averaging the exponential part gives

$$\left\langle \exp( -iQr_{ij} \cos \gamma ) \right\rangle = \frac{1}{2\pi r_{ij}} \int_0^\pi \exp\left( -iQr_{ij} \cos\gamma
    \right) ~2 r_{ij} ~\mathrm{d}\gamma$$

$$= \frac{1}{\pi} \int_0^\pi \exp\left( -iQr_{ij} \cos\gamma \right) ~\mathrm{d}\gamma$$

WolframAlpha says [this integrates to a Bessel function](https://www.wolframalpha.com/input?i=integrate+%281%2Fpi%29*e%5E%28-i*k*x*cos%28gamma%29%29+from+gamma%3D0+to+gamma%3Dpi) $J_0(Qr)$.

I double-checked the 3D case, and [WolframAlpha agrees that it reduces to sinc(Qr)](https://www.wolframalpha.com/input?i=integrate+1%2F2+e%5E%28-i*k*x*cos%28gamma%29%29*sin%28gamma%29+from+gamma%3D0+to+gamma%3Dpi).

Here is a reference (found after doing the derivation myself) that agrees with my assessment that this should be a Bessel function $J_0(Qr)$.

- The Debye Scattering Formula in $n$ Dimensions, Thomas Wieder. J. Math. Comput. Sci. 2 (2012), No. 4, 1086-1090. http://www.scik.org/index.php/jmcs/article/viewFile/263/120

![image](https://user-images.githubusercontent.com/3943761/177048044-f1134520-371b-4b13-98cb-908b8e9ffea2.png)

**Comment by bdice** [comment]
To resolve this, I see three options:
- Upgrade freud to require C++17 and use `cyl_bessel_j(0, qr)` from `<cmath>`. https://en.cppreference.com/w/cpp/numeric/special_functions/cyl_bessel_j
  - I strongly prefer this option if it is viable. Note: Our manylinux image base may need to be updated to support C++17. We'll get lots of new C++ features as a benefit, and we don't have to worry about the quality of the implementation of `cyl_bessel_j`.
- Copy some other implementation of `cyl_bessel_j` from an acceptably-licensed source and include a reference.
- Write a special function in [utils.h](https://github.com/glotzerlab/freud/blob/master/cpp/util/utils.h) that computes a series expansion. The snippet below is copied from the cppreference link above. I leave it as an exercise to determine how many terms are required in the expansion (this uses 6 terms). 😉

```cpp
#include <cmath>
#include <iostream>
int main()
{
    // spot check for ν == 0
    double x = 1.2345;
    std::cout << "J_0(" << x << ") = " << std::cyl_bessel_j(0, x) << '\n';
 
    // series expansion for J_0
    double fct = 1;
    double sum = 0;
    for(int k = 0; k < 6; fct*=++k) {
        sum += std::pow(-1, k)*std::pow((x/2),2*k) / std::pow(fct,2);
        std::cout << "sum = " << sum << '\n';
    }        
}
```

This page from Boost explores numerical error in Bessel functions and may be helpful: https://www.boost.org/doc/libs/1_79_0/libs/math/doc/html/math_toolkit/bessel/bessel_first.html

**Comment by tommy-waltmann** [comment]
Seconded, we should proceed by trying to update the C++ standard so we can use the built-in bessel implementation. We'll need to address this before we make another release, as the improper implementation is on master as of now.

**Comment by tommy-waltmann** [comment]
Boost has an implementation of `cyl_bessel_j` we may be able to use in lieu of the standard library: https://github.com/boostorg/math/blob/develop/include/boost/math/special_functions/bessel.hpp . It's just a question of whether we want such a large dependency as a submodule.

**Comment by joaander** [comment]
Boost is far more of a headache than it is worth. I see no problems in updating to C++17. HOOMD started using C++17 in the host compiler starting with 3.0-beta.13.

**Comment by tommy-waltmann** [comment]
The issue is in support for the special math functions in C++17, see #987 .
