### ISSUE TITLE
Use more descriptive names for the `neighbors` in `EnvironmentCluster` and `EnvironmentMotifMatch`

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/freud#989]
1. We should definitely rename `neighbors` parameters of `EnvironmentMotifMatch` to `env_neighbors`. The current `neighbors` are functionally the same as the `env_neighbors` of `EnvironmentCluster`, not the `neighbors`, so making these match will help improve clarity on how these work.
2. After that, we may want to consider using another prefix for the `neighbors` parameter of `EnvironmentCluster` to more clearly delineate the purpose of these neighbors. Even `env_neighbors` may be somewhat ambiguous to interpret, and we may want to choose a different name there as well. However, this step is optional depending on whether we can come up with names that improve clarity. Step 1 is definitely a plus.

**Comment by tommy-waltmann** [comment]
We could rename `neighbors` to `cluster_neighbors` to indicate that those neighbors define the clusters. How does that sound?

**Comment by vyasr** [comment]
Works for me. That seems about as clear as we can get. The best thing we can do is to improve the docstrings once that's done. The description of the `EnvironmentCluster` class seems to be doing a pretty good job of describing the difference between `neighbors` and `env_neighbors`, but the parameter descriptions of `neighbors` and `env_neighbors` aren't super informative and it would be good to copy-paste a bit of the description for them to make them clearer. [The corresponding C++ documentation looks altogether out of date](https://github.com/glotzerlab/freud/blob/master/cpp/environment/MatchEnv.h#L255) and would also benefit from the revamp after the parameters are renamed.

**Comment by tommy-waltmann** [comment]
closed via #1062
